### ISSUE TITLE
[Mobile] issue with links when you enter a url and then try to give it a human readable label while using LinkStyleButton

### ISSUE THREAD

**Issue by mwothman** [singerdmx/flutter-quill#1042]
the following video will demonstrate how to reproduce this issue 
i am using flutter version 3.3.4 on stable channel, and using the example app on flutter_quill version 6.1.11 at the time of recording, the recording from an iOS simulator this can happen in a real device android/iOS

https://user-images.githubusercontent.com/56353593/210167855-31e23160-9123-451a-bcb4-6da475aa2ddf.mov

and this is this is the exception i receive 

```

======== Exception caught by rendering library =====================================================
The following assertion was thrown during paint():
The provided text position is not in the current node
'package:flutter_quill/src/widgets/text_line.dart':
Failed assertion: line 1157 pos 12: 'container.containsOffset(position.offset)'

The relevant error-causing widget was: 
  QuillEditor QuillEditor:file:///Users/myMac/Downloads/flutter-quill-master/example/lib/pages/home_page.dart:164:14
When the exception was thrown, this was the stack: 
#2      RenderEditableTextLine.globalToLocalPosition (package:flutter_quill/src/widgets/text_line.dart:1157:12)
#3      RenderEditor._getOffsetForCaret (package:flutter_quill/src/widgets/editor.dart:870:33)
#4      RenderEditor._updateSelectionExtentsVisibility (package:flutter_quill/src/widgets/editor.dart:860:23)
#5      RenderEditor.paint (package:flutter_quill/src/widgets/editor.dart:1257:5)
#6      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2796:7)
#7      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:239:13)
#8      RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:144:15)
#9      PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:460:12)
#10     RenderLeaderLayer.paint (package:flutter/src/rendering/proxy_box.dart:4736:13)
#11     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2796:7)
#12     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:239:13)
#13     _RenderSingleChildViewport.paint.paintContents (package:flutter_quill/src/widgets/quill_single_child_scroll_view.dart:239:17)
#14     PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:460:12)
#15     PaintingContext.pushClipRect (package:flutter/src/rendering/object.dart:520:7)
#16     _RenderSingleChildViewport.paint (package:flutter_quill/src/widgets/quill_single_child_scroll_view.dart:243:40)
#17     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2796:7)
#18     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:155:11)
#19     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:98:5)
#20     PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:1116:31)
#21     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:515:19)
#22     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:884:13)
#23     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:378:5)
#24     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1175:15)
#25     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1104:9)
#26     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1015:5)
#27     _invoke (dart:ui/hooks.dart:148:13)
#28     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:318:5)
#29     _drawFrame (dart:ui/hooks.dart:115:31)
(elided 2 frames from class _AssertionError)
The following RenderObject was being processed when the exception was fired: RenderEditor#fb57c relayoutBoundary=up19
...  needs compositing
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(0.0<=w<=398.0, 0.0<=h<=Infinity)
...  size: Size(398.0, 21.0)
RenderObject: RenderEditor#fb57c relayoutBoundary=up19
  needs compositing
  parentData: <none> (can use size)
  constraints: BoxConstraints(0.0<=w<=398.0, 0.0<=h<=Infinity)
  size: Size(398.0, 21.0)
...  child 1: RenderEditableTextLine#5b3b6 relayoutBoundary=up20
...    needs compositing
...    parentData: offset=Offset(0.0, 0.0) (can use size)
...    constraints: BoxConstraints(w=398.0, 0.0<=h<=Infinity)
...    layer: OffsetLayer#d05b0
...      engine layer: OffsetEngineLayer#5bda1
...      handles: 2
...      offset: Offset(0.0, 0.0)
...    size: Size(398.0, 21.0)
...    body: RenderParagraphProxy#f9e48 relayoutBoundary=up21
...      parentData: offset=Offset(0.0, 0.0) (can use size)
...      constraints: BoxConstraints(w=398.0, 0.0<=h<=Infinity)
...      size: Size(398.0, 21.0)
...      child: RenderParagraph#e0697 relayoutBoundary=up22
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(w=398.0, 0.0<=h<=Infinity)
...        semantic boundary
...        size: Size(398.0, 21.0)
...        textAlign: start
...        textDirection: ltr
...        softWrap: wrapping at box width
...        overflow: clip
...        locale: en_US
...        maxLines: unlimited
...        text: TextSpan
...          debugLabel: ((englishLike bodyMedium 2014).merge(blackCupertino bodyMedium)).copyWith
...          inherit: false
...          color: Color(0xdd000000)
...          family: .SF UI Text
...          size: 16.0
...          weight: 400
...          baseline: alphabetic
...          height: 1.3x
...          decoration: TextDecoration.none
====================================================================================================

```

**Comment by rafael001001** [comment]
Same error for me when using delete() on a quill controller. Any updates on this?

**Comment by hoangsang17th** [comment]
It was fixed. Can you try again?

**Comment by mwothman** [comment]
i had a chance to test it out again, it appears to be working but throws an exceptions after using links

https://github.com/singerdmx/flutter-quill/assets/56353593/58745d9c-9104-4c9e-a318-257c20a11047

my flutter version is 3.13.2 on stable channel 

```
======== Exception caught by rendering library =====================================================
The following assertion was thrown during paint():
The provided text position is not in the current node
'package:flutter_quill/src/widgets/text_line.dart':
Failed assertion: line 1222 pos 12: 'container.containsOffset(position.offset)'

The relevant error-causing widget was: 
  QuillEditor QuillEditor:file:///Users/ls-mac22/Downloads/flutter-quill-master/example/lib/pages/home_page.dart:178:26
When the exception was thrown, this was the stack: 
#2      RenderEditableTextLine.globalToLocalPosition (package:flutter_quill/src/widgets/text_line.dart:1222:12)
#3      RenderEditor._getOffsetForCaret (package:flutter_quill/src/widgets/editor.dart:939:33)
#4      RenderEditor._updateSelectionExtentsVisibility (package:flutter_quill/src/widgets/editor.dart:929:23)
#5      RenderEditor.paint (package:flutter_quill/src/widgets/editor.dart:1329:5)
#6      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
#7      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:252:13)
#8      RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
#9      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
#10     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:252:13)
#11     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
#12     PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:472:12)
#13     RenderLeaderLayer.paint (package:flutter/src/rendering/proxy_box.dart:4755:13)
#14     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
#15     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:252:13)
#16     _RenderSingleChildViewport.paint.paintContents (package:flutter_quill/src/widgets/quill_single_child_scroll_view.dart:239:17)
#17     _RenderSingleChildViewport.paint (package:flutter_quill/src/widgets/quill_single_child_scroll_view.dart:252:9)
#18     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
#19     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:168:11)
#20     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:111:5)
#21     PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:1144:31)
#22     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:496:19)
#23     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:918:13)
#24     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:360:5)
#25     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1297:15)
#26     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1227:9)
#27     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1085:5)
#28     _invoke (dart:ui/hooks.dart:170:13)
#29     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:401:5)
#30     _drawFrame (dart:ui/hooks.dart:140:31)
(elided 2 frames from class _AssertionError)
The following RenderObject was being processed when the exception was fired: RenderEditor#28931 relayoutBoundary=up20
...  needs compositing
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(0.0<=w<=398.0, 0.0<=h<=Infinity)
...  size: Size(398.0, 21.0)
RenderObject: RenderEditor#28931 relayoutBoundary=up20
  needs compositing
  parentData: <none> (can use size)
  constraints: BoxConstraints(0.0<=w<=398.0, 0.0<=h<=Infinity)
  size: Size(398.0, 21.0)
...  child 1: RenderEditableTextLine#0cd60 relayoutBoundary=up21
...    needs compositing
...    parentData: offset=Offset(0.0, 0.0) (can use size)
...    constraints: BoxConstraints(w=398.0, 0.0<=h<=Infinity)
...    layer: OffsetLayer#ab252
...      engine layer: OffsetEngineLayer#41887
...      handles: 2
...      offset: Offset(0.0, 0.0)
...    size: Size(398.0, 21.0)
...    body: RenderParagraphProxy#55aa8 relayoutBoundary=up22
...      parentData: offset=Offset(0.0, 0.0) (can use size)
...      constraints: BoxConstraints(w=398.0, 0.0<=h<=Infinity)
...      size: Size(398.0, 21.0)
...      child: RenderParagraph#6263c relayoutBoundary=up23
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(w=398.0, 0.0<=h<=Infinity)
...        semantics node: SemanticsNode#135
...          STALE
...          owner: null
...          Rect.fromLTRB(0.0, 0.0, 398.0, 21.0)
...        semantic boundary
...        size: Size(398.0, 21.0)
...        textAlign: start
...        textDirection: ltr
...        softWrap: wrapping at box width
...        overflow: clip
...        locale: en_US
...        maxLines: unlimited
...        text: TextSpan
...          debugLabel: ((englishLike bodyMedium 2014).merge(blackCupertino bodyMedium)).copyWith
...          inherit: false
...          color: Color(0xdd000000)
...          family: .SF UI Text
...          size: 16.0
...          weight: 400
...          baseline: alphabetic
...          height: 1.3x
...          decoration: TextDecoration.none
====================================================================================================

======== Exception caught by scheduler library =====================================================
The following assertion was thrown during a scheduler callback:
'package:flutter_quill/src/widgets/editor.dart': Failed assertion: line 1070 pos 12: 'extentChild != null': is not true.

When the exception was thrown, this was the stack: 
#2      RenderEditor.getEndpointsForSelection (package:flutter_quill/src/widgets/editor.dart:1070:12)
#3      RenderEditor.getOffsetToRevealCursor (package:flutter_quill/src/widgets/editor.dart:1415:23)
#4      RawEditorState._showCaretOnScreen.<anonymous closure> (package:flutter_quill/src/widgets/raw_editor.dart:1340:37)
#5      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1297:15)
#6      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1236:9)
#7      SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1085:5)
#8      _invoke (dart:ui/hooks.dart:170:13)
#9      PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:401:5)
#10     _drawFrame (dart:ui/hooks.dart:140:31)
(elided 2 frames from class _AssertionError)
====================================================================================================

======== Exception caught by foundation library ====================================================
The following assertion was thrown while dispatching notifications for FocusNode:
Range end 18 is out of text of length 7
'package:flutter/src/services/text_input.dart':
Failed assertion: line 965 pos 12: 'range.end >= 0 && range.end <= text.length'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.yml

When the exception was thrown, this was the stack: 
#2      TextEditingValue._textRangeIsValid (package:flutter/src/services/text_input.dart:965:12)
#3      TextEditingValue.toJSON (package:flutter/src/services/text_input.dart:918:12)
#4      _PlatformTextInputControl.setEditingState (package:flutter/src/services/text_input.dart:2256:13)
#5      TextInput._setEditingState (package:flutter/src/services/text_input.dart:1945:15)
#6      TextInputConnection.setEditingState (package:flutter/src/services/text_input.dart:1369:25)
#7      RawEditorStateTextInputClientMixin.openConnectionIfNeeded (package:flutter_quill/src/widgets/raw_editor/raw_editor_state_text_input_client_mixin.dart:73:29)
#8      RawEditorStateTextInputClientMixin.openOrCloseConnection (package:flutter_quill/src/widgets/raw_editor/raw_editor_state_text_input_client_mixin.dart:40:7)
#9      RawEditorState._handleFocusChanged (package:flutter_quill/src/widgets/raw_editor.dart:1288:5)
#10     ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:403:24)
#11     FocusNode._notify (package:flutter/src/widgets/focus_manager.dart:1050:5)
#12     FocusManager._applyFocusChange (package:flutter/src/widgets/focus_manager.dart:1646:12)
(elided 4 frames from class _AssertionError and dart:async)
The FocusNode sending notification was: FocusNode#a33d3([PRIMARY FOCUS])
  context: Focus
  PRIMARY FOCUS
====================================================================================================

======== Exception caught by rendering library =====================================================
The following assertion was thrown during paint():
The provided text position is not in the current node
'package:flutter_quill/src/widgets/text_line.dart':
Failed assertion: line 1222 pos 12: 'container.containsOffset(position.offset)'

The relevant error-causing widget was: 
  QuillEditor QuillEditor:file:///Users/ls-mac22/Downloads/flutter-quill-master/example/lib/pages/home_page.dart:178:26
When the exception was thrown, this was the stack: 
#2      RenderEditableTextLine.globalToLocalPosition (package:flutter_quill/src/widgets/text_line.dart:1222:12)
#3      RenderEditor._getOffsetForCaret (package:flutter_quill/src/widgets/editor.dart:939:33)
#4      RenderEditor._updateSelectionExtentsVisibility (package:flutter_quill/src/widgets/editor.dart:929:23)
#5      RenderEditor.paint (package:flutter_quill/src/widgets/editor.dart:1329:5)
#6      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
#7      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:252:13)
#8      RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
#9      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
#10     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:252:13)
#11     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
#12     PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:472:12)
#13     RenderLeaderLayer.paint (package:flutter/src/rendering/proxy_box.dart:4755:13)
#14     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
#15     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:252:13)
#16     _RenderSingleChildViewport.paint.paintContents (package:flutter_quill/src/widgets/quill_single_child_scroll_view.dart:239:17)
#17     _RenderSingleChildViewport.paint (package:flutter_quill/src/widgets/quill_single_child_scroll_view.dart:252:9)
#18     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
#19     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:168:11)
#20     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:111:5)
#21     PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:1144:31)
#22     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:496:19)
#23     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:918:13)
#24     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:360:5)
#25     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1297:15)
#26     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1227:9)
#27     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1085:5)
#28     _invoke (dart:ui/hooks.dart:170:13)
#29     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:401:5)
#30     _drawFrame (dart:ui/hooks.dart:140:31)
(elided 2 frames from class _AssertionError)
The following RenderObject was being processed when the exception was fired: RenderEditor#28931 relayoutBoundary=up20
...  needs compositing
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(0.0<=w<=398.0, 0.0<=h<=Infinity)
...  size: Size(398.0, 21.0)
RenderObject: RenderEditor#28931 relayoutBoundary=up20
  needs compositing
  parentData: <none> (can use size)
  constraints: BoxConstraints(0.0<=w<=398.0, 0.0<=h<=Infinity)
  size: Size(398.0, 21.0)
...  child 1: RenderEditableTextLine#0cd60 relayoutBoundary=up21
...    needs compositing
...    parentData: offset=Offset(0.0, 0.0) (can use size)
...    constraints: BoxConstraints(w=398.0, 0.0<=h<=Infinity)
...    layer: OffsetLayer#ab252
...      engine layer: OffsetEngineLayer#7ed32
...      handles: 2
...      offset: Offset(0.0, 0.0)
...    size: Size(398.0, 21.0)
...    body: RenderParagraphProxy#55aa8 relayoutBoundary=up22
...      parentData: offset=Offset(0.0, 0.0) (can use size)
...      constraints: BoxConstraints(w=398.0, 0.0<=h<=Infinity)
...      size: Size(398.0, 21.0)
...      child: RenderParagraph#8a6c4 relayoutBoundary=up23
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(w=398.0, 0.0<=h<=Infinity)
...        semantic boundary
...        size: Size(398.0, 21.0)
...        textAlign: start
...        textDirection: ltr
...        softWrap: wrapping at box width
...        overflow: clip
...        locale: en_US
...        maxLines: unlimited
...        text: TextSpan
...          debugLabel: ((englishLike bodyMedium 2014).merge(blackCupertino bodyMedium)).copyWith
...          inherit: false
...          color: Color(0xdd000000)
...          family: .SF UI Text
...          size: 16.0
...          weight: 400
...          baseline: alphabetic
...          height: 1.3x
...          decoration: TextDecoration.none
====================================================================================================
```

**Comment by freshtechtips** [comment]
Thank you for the report, this issue has been open for a while and since there are no interactions with it, we had to close it

but if you still facing this issue, or other issues or you have any other questions, feel free to contact us anytime you want.

**Comment by captaingerhard** [comment]
I am having the issue as well when I save a shorter text then before. On submitting the textlink I am getting the following exception:

`_AssertionError ('package:flutter/src/services/text_input.dart': Failed assertion: line 1159 pos 7: 'range.end >= 0 && range.end <= text.length': Range end 297 is out of text of length 260)`

and after that it saves the last characters of the old text dependent on the new text length.
