### ISSUE TITLE
type 'Null' is not a subtype of type 'Block' in type cast

### ISSUE THREAD

**Issue by ddxl123** [singerdmx/flutter-quill#1260]
When there is at least one character or embedded block in the edited content, and the cursor is at the very beginning, clicking the undo button will result in the following error:
```

======== Exception caught by foundation library ====================================================
The following _TypeError was thrown while dispatching notifications for QuillController:
type 'Null' is not a subtype of type 'Block' in type cast

When the exception was thrown, this was the stack: 
#0      Document.queryChild (package:flutter_quill/src/models/documents/document.dart:192:28)
#1      Document.collectStyle (package:flutter_quill/src/models/documents/document.dart:157:17)
#2      QuillController.getSelectionStyle (package:flutter_quill/src/widgets/controller.dart:98:10)
#3      _QuillFontFamilyButtonState._selectionStyle (package:flutter_quill/src/widgets/toolbar/quill_font_family_button.dart:70:50)
#4      _QuillFontFamilyButtonState._didChangeEditingValue (package:flutter_quill/src/widgets/toolbar/quill_font_family_button.dart:95:23)
#5      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:403:24)
#6      QuillController.updateSelection (package:flutter_quill/src/widgets/controller.dart:350:5)
#7      QuillController._handleHistoryChange (package:flutter_quill/src/widgets/controller.dart:197:7)
#8      QuillController.undo (package:flutter_quill/src/widgets/controller.dart:187:7)
#9      _HistoryButtonState._changeHistory (package:flutter_quill/src/widgets/toolbar/history_button.dart:79:27)
#10     QuillIconButton.build.<anonymous closure> (package:flutter_quill/src/widgets/toolbar/quill_icon_button.dart:44:24)
#11     _InkResponseState.handleTap (package:flutter/src/material/ink_well.dart:1154:21)
#12     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:275:24)
#13     TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:654:11)
#14     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:311:5)
#15     BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:281:7)
#16     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:167:27)
#17     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:469:20)
#18     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:445:22)
#19     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:331:11)
#20     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:400:7)
#21     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:363:5)
#22     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:320:7)
#23     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:293:9)
#24     _invoke1 (dart:ui/hooks.dart:158:13)
#25     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:382:7)
#26     _dispatchPointerDataPacket (dart:ui/hooks.dart:91:31)
The QuillController sending notification was: Instance of 'QuillController'
====================================================================================================
```

**Comment by singerdmx** [comment]
Is it still an issue in latest version?
