### ISSUE TITLE
[Mobile] Problems with new QuillProvider (QuillProvider.updateShouldNotify)

### ISSUE THREAD

**Issue by mark8044** [singerdmx/flutter-quill#1447]
Im trying to migrate to the new QuillProvider but having significant problems:

Has anyone seen this or have any idea what to do?

```
======== Exception caught by widgets library =======================================================
The following bool object was thrown building KeyedSubtree-[GlobalKey#2e947]:
  false

The relevant error-causing widget was: 
  Scaffold Scaffold:file:////editor_quill.dart:946:18
When the exception was thrown, this was the stack: 
#0      QuillProvider.updateShouldNotify (package:flutter_quill/src/widgets/utils/provider.dart:21:5)
#1      InheritedElement.updated (package:flutter/src/widgets/framework.dart:5847:37)
#2      ProxyElement.update (package:flutter/src/widgets/framework.dart:5627:5)
#3      Element.updateChild (package:flutter/src/widgets/framework.dart:3685:15)
#4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322:16)
#5      Element.rebuild (package:flutter/src/widgets/framework.dart:5016:7)
#6      StatelessElement.update (package:flutter/src/widgets/framework.dart:5373:5)
#7      Element.updateChild (package:flutter/src/widgets/framework.dart:3685:15)
#8      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322:16)
#9      Element.rebuild (package:flutter/src/widgets/framework.dart:5016:7)
#10     StatelessElement.update (package:flutter/src/widgets/framework.dart:5373:5)
#11     Element.updateChild (package:flutter/src/widgets/framework.dart:3685:15)
#12     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322:16)
#13     Element.rebuild (package:flutter/src/widgets/framework.dart:5016:7)
#14     ProxyElement.update (package:flutter/src/widgets/framework.dart:5628:5)
#15     Element.updateChild (package:flutter/src/widgets/framework.dart:3685:15)
#16     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322:16)
#17     Element.rebuild (package:flutter/src/widgets/framework.dart:5016:7)
#18     ProxyElement.update (package:flutter/src/widgets/framework.dart:5628:5)
#19     Element.updateChild (package:flutter/src/widgets/framework.dart:3685:15)
#20     Element.updateChildren (package:flutter/src/widgets/framework.dart:3834:32)
#21     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6594:17)
#22     Element.updateChild (package:flutter/src/widgets/framework.dart:3685:15)
#23     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322:16)
#24     Element.rebuild (package:flutter/src/widgets/framework.dart:5016:7)
#25     ProxyElement.update (package:flutter/src/widgets/framework.dart:5628:5)
#26     Element.updateChild (package:flutter/src/widgets/framework.dart:3685:15)
#27     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322:16)
#28     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5462:11)
#29     Element.rebuild (package:flutter/src/widgets/framework.dart:5016:7)
#30     StatefulElement.update (package:flutter/src/widgets/framework.dart:5485:5)
#31     Element.updateChild (package:flutter/src/widgets/framework.dart:3685:15)
#32     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322:16)
#33     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5462:11)
#34     Element.rebuild (package:flutter/src/widgets/framework.dart:5016:7)
#35     StatefulElement.update (package:flutter/src/widgets/framework.dart:5485:5)
#36     Element.updateChild (package:flutter/src/widgets/framework.dart:3685:15)
#37     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322:16)
#38     Element.rebuild (package:flutter/src/widgets/framework.dart:5016:7)
#39     ProxyElement.update (package:flutter/src/widgets/framework.dart:5628:5)
#40     Element.updateChild (package:flutter/src/widgets/framework.dart:3685:15)
#41     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322:16)
#42     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5462:11)
#43     Element.rebuild (package:flutter/src/widgets/framework.dart:5016:7)
#44     StatefulElement.update (package:flutter/src/widgets/framework.dart:5485:5)
#45     Element.updateChild (package:flutter/src/widgets/framework.dart:3685:15)
#46     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6441:14)
#47     Element.updateChild (package:flutter/src/widgets/framework.dart:3685:15)
#48     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322:16)
#49     Element.rebuild (package:flutter/src/widgets/framework.dart:5016:7)
#50     ProxyElement.update (package:flutter/src/widgets/framework.dart:5628:5)
#51     Element.updateChild (package:flutter/src/widgets/framework.dart:3685:15)
#52     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6441:14)
#53     Element.updateChild (package:flutter/src/widgets/framework.dart:3685:15)
#54     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322:16)
#55     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5462:11)
#56     Element.rebuild (package:flutter/src/widgets/framework.dart:5016:7)
#57     StatefulElement.update (package:flutter/src/widgets/framework.dart:5485:5)
#58     Element.updateChild (package:flutter/src/widgets/framework.dart:3685:15)
#59     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322:16)
#60     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5462:11)
#61     Element.rebuild (package:flutter/src/widgets/framework.dart:5016:7)
#62     StatefulElement.update (package:flutter/src/widgets/framework.dart:5485:5)
#63     Element.updateChild (package:flutter/src/widgets/framework.dart:3685:15)
#64     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322:16)
#65     Element.rebuild (package:flutter/src/widgets/framework.dart:5016:7)
#66     ProxyElement.update (package:flutter/src/widgets/framework.dart:5628:5)
#67     Element.updateChild (package:flutter/src/widgets/framework.dart:3685:15)
#68     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322:16)
#69     Element.rebuild (package:flutter/src/widgets/framework.dart:5016:7)
#70     ProxyElement.update (package:flutter/src/widgets/framework.dart:5628:5)
#71     Element.updateChild (package:flutter/src/widgets/framework.dart:3685:15)
#72     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322:16)
#73     Element.rebuild (package:flutter/src/widgets/framework.dart:5016:7)
#74     ProxyElement.update (package:flutter/src/widgets/framework.dart:5628:5)
#75     Element.updateChild (package:flutter/src/widgets/framework.dart:3685:15)
#76     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322:16)
#77     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5462:11)
#78     Element.rebuild (package:flutter/src/widgets/framework.dart:5016:7)
#79     StatefulElement.update (package:flutter/src/widgets/framework.dart:5485:5)
#80     Element.updateChild (package:flutter/src/widgets/framework.dart:3685:15)
#81     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322:16)
#82     Element.rebuild (package:flutter/src/widgets/framework.dart:5016:7)
#83     ProxyElement.update (package:flutter/src/widgets/framework.dart:5628:5)
#84     Element.updateChild (package:flutter/src/widgets/framework.dart:3685:15)
#85     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322:16)
#86     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5462:11)
#87     Element.rebuild (package:flutter/src/widgets/framework.dart:5016:7)
#88     StatefulElement.update (package:flutter/src/widgets/framework.dart:5485:5)
#89     Element.updateChild (package:flutter/src/widgets/framework.dart:3685:15)
#90     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322:16)
#91     Element.rebuild (package:flutter/src/widgets/framework.dart:5016:7)
#92     ProxyElement.update (package:flutter/src/widgets/framework.dart:5628:5)
#93     Element.updateChild (package:flutter/src/widgets/framework.dart:3685:15)
#94     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322:16)
#95     Element.rebuild (package:flutter/src/widgets/framework.dart:5016:7)
#96     StatelessElement.update (package:flutter/src/widgets/framework.dart:5373:5)
#97     Element.updateChild (package:flutter/src/widgets/framework.dart:3685:15)
#98     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322:16)
#99     Element.rebuild (package:flutter/src/widgets/framework.dart:5016:7)
#100    ProxyElement.update (package:flutter/src/widgets/framework.dart:5628:5)
#101    Element.updateChild (package:flutter/src/widgets/framework.dart:3685:15)
#102    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322:16)
#103    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5462:11)
#104    Element.rebuild (package:flutter/src/widgets/framework.dart:5016:7)
#105    StatefulElement.update (package:flutter/src/widgets/framework.dart:5485:5)
#106    Element.updateChild (package:flutter/src/widgets/framework.dart:3685:15)
#107    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6441:14)
#108    Element.updateChild (package:flutter/src/widgets/framework.dart:3685:15)
#109    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322:16)
#110    Element.rebuild (package:flutter/src/widgets/framework.dart:5016:7)
#111    ProxyElement.update (package:flutter/src/widgets/framework.dart:5628:5)
#112    Element.updateChild (package:flutter/src/widgets/framework.dart:3685:15)
#113    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6441:14)
#114    Element.updateChild (package:flutter/src/widgets/framework.dart:3685:15)
#115    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322:16)
#116    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5462:11)
#117    Element.rebuild (package:flutter/src/widgets/framework.dart:5016:7)
#118    StatefulElement.update (package:flutter/src/widgets/framework.dart:5485:5)
#119    Element.updateChild (package:flutter/src/widgets/framework.dart:3685:15)
#120    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322:16)
#121    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5462:11)
#122    Element.rebuild (package:flutter/src/widgets/framework.dart:5016:7)
#123    StatefulElement.update (package:flutter/src/widgets/framework.dart:5485:5)
#124    Element.updateChild (package:flutter/src/widgets/framework.dart:3685:15)
#125    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322:16)
#126    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5462:11)
#127    Element.rebuild (package:flutter/src/widgets/framework.dart:5016:7)
#128    StatefulElement.update (package:flutter/src/widgets/framework.dart:5485:5)
#129    Element.updateChild (package:flutter/src/widgets/framework.dart:3685:15)
#130    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322:16)
#131    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5462:11)
#132    Element.rebuild (package:flutter/src/widgets/framework.dart:5016:7)
#133    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2779:19)
#134    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:916:21)
#135    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:360:5)
#136    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1297:15)
#137    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1227:9)
#138    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1085:5)
#139    _invoke (dart:ui/hooks.dart:170:13)
#140    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:401:5)
#141    _drawFrame (dart:ui/hooks.dart:140:31)
```

```
         child: Scaffold( 
            resizeToAvoidBottomInset:false,
            body: QuillProvider(
              configurations: QuillConfigurations(
                  controller: _controller,
                  editorConfigurations: const QuillEditorConfigurations(
                    readOnly: false,
                  ),
              ),
              child: Column(. ...
```

**Comment by freshtechtips** [comment]
This issue should be fixed in the next pull request that I will send in a moments

**Comment by freshtechtips** [comment]
Please upgrade to
`7.6.1`
version

The issue has been fixed.
