### ISSUE TITLE
Android14 paste image unreadable code

### ISSUE THREAD

**Issue by luoyi58624** [singerdmx/flutter-quill#1650]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

9.1.1

### Steps to reproduce

https://github.com/singerdmx/flutter-quill/assets/46178521/4612a935-6cf6-488c-94c9-734480936956

### Expected results

show image

### Actual results

image unreadable code

### Code sample

import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:flutter_quill/flutter_quill.dart';
import 'package:flutter_quill_extensions/flutter_quill_extensions.dart';

void main() {
  runApp(const MainApp());
}

class MainApp extends StatefulWidget {
  const MainApp({super.key});

  @override
  State<MainApp> createState() => _MainAppState();
}

class _MainAppState extends State<MainApp> {
  QuillController controller = QuillController.basic();

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      localizationsDelegates: const [
        GlobalWidgetsLocalizations.delegate,
        GlobalMaterialLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
      ],
      supportedLocales: const [
        Locale('zh', 'CH'),
        Locale('en', 'US'),
      ],
      locale: const Locale('zh', 'CN'),
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Editor'),
        ),
        body: Column(
          children: [
            QuillToolbar.simple(
              configurations: QuillSimpleToolbarConfigurations(
                controller: controller,
                sharedConfigurations: const QuillSharedConfigurations(),
                embedButtons: FlutterQuillEmbeds.toolbarButtons(),
              ),
            ),
            Expanded(
              child: Padding(
                padding: const EdgeInsets.all(8.0),
                child: QuillEditor.basic(
                  configurations: QuillEditorConfigurations(
                    controller: controller,
                    readOnly: false,
                    sharedConfigurations: const QuillSharedConfigurations(),
                    embedBuilders: kIsWeb ? FlutterQuillEmbeds.editorWebBuilders() : FlutterQuillEmbeds.editorBuilders(),
                  ),
                ),
              ),
            )
          ],
        ),
      ),
    );
  }
}

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by luoyi58624** [comment]
<img width="1075" alt="image" src="https://github.com/singerdmx/flutter-quill/assets/46178521/64c19df7-5e80-490e-b86f-f0122a45857b">
<img width="1368" alt="image" src="https://github.com/singerdmx/flutter-quill/assets/46178521/958908a6-8803-4d5b-bf0a-45e39ef323f6">

**Comment by luoyi58624** [comment]
<img width="1635" alt="image" src="https://github.com/singerdmx/flutter-quill/assets/46178521/4ada2398-fffa-499f-bc24-f90a7a1e6794">
W/MIUIScout App(15137):  (Current message: duration=2502ms seq=432 h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0)
D/AppScoutStateMachine(15137): dump trace dirName = 2023-12-29-18-15-13-15137-APP_SCOUT_WARNING-com.example.example
W/MIUIScout App(15137): Event:APP_SCOUT_WARNING Thread:main backtrace:
W/MIUIScout App(15137):     at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:180)
W/MIUIScout App(15137):     at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:543)
W/MIUIScout App(15137):     at java.lang.StringBuilder.append(StringBuilder.java:186)
W/MIUIScout App(15137):     at java.util.Formatter$FormatSpecifierParser.<init>(Formatter.java:2757)
W/MIUIScout App(15137):     at java.util.Formatter.parse(Formatter.java:2711)
W/MIUIScout App(15137):     at java.util.Formatter.format(Formatter.java:2660)
W/MIUIScout App(15137):     at java.util.Formatter.format(Formatter.java:2614)
W/MIUIScout App(15137):     at java.lang.String.format(String.java:4017)
W/MIUIScout App(15137):     at org.json.JSONStringer.string(JSONStringer.java:352)
W/MIUIScout App(15137):     at org.json.JSONStringer.value(JSONStringer.java:261)
W/MIUIScout App(15137):     at org.json.JSONObject.writeTo(JSONObject.java:734)
W/MIUIScout App(15137):     at org.json.JSONStringer.value(JSONStringer.java:246)
W/MIUIScout App(15137):     at org.json.JSONArray.writeTo(JSONArray.java:616)
W/MIUIScout App(15137):     at org.json.JSONArray.toString(JSONArray.java:587)
W/MIUIScout App(15137):     at io.flutter.plugin.common.JSONMessageCodec.encodeMessage(JSONMessageCodec.java:41)
W/MIUIScout App(15137):     at io.flutter.plugin.common.JSONMethodCodec.encodeSuccessEnvelope(JSONMethodCodec.java:65)
W/MIUIScout App(15137):     at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:272)
W/MIUIScout App(15137):     at io.flutter.embedding.engine.systemchannels.PlatformChannel$1.onMethodCall(PlatformChannel.java:169)
W/MIUIScout App(15137):     at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
W/MIUIScout App(15137):     at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
W/MIUIScout App(15137):     at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
W/MIUIScout App(15137):     at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
W/MIUIScout App(15137):     at android.os.Handler.handleCallback(Handler.java:958)
W/MIUIScout App(15137):     at android.os.Handler.dispatchMessage(Handler.java:99)
W/MIUIScout App(15137):     at android.os.Looper.loopOnce(Looper.java:224)
W/MIUIScout App(15137):     at android.os.Looper.loop(Looper.java:318)
W/MIUIScout App(15137):     at android.app.ActivityThread.main(ActivityThread.java:8669)
W/MIUIScout App(15137):     at java.lang.reflect.Method.invoke(Native Method)
W/MIUIScout App(15137):     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
W/MIUIScout App(15137):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
I/example.example(15137): Thread[4,tid=15146,WaitingInMainSignalCatcherLoop,Thread*=0xb40000766c411800,peer=0x14640000,"Signal Catcher"]: reacting to signal 3

**Comment by ellet0** [comment]
Hi there, doest the issue happen on older versions of flutter quill?

**Comment by luoyi58624** [comment]
Currently project using 8.6.1, found that the latest version still has this problem
