### ISSUE TITLE
Strange behavior when compiling on Android

### ISSUE THREAD

**Issue by 4ikosa** [singerdmx/flutter-quill#1655]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

9.1.1

### Steps to reproduce

flutter create test_quill
flutter pub add flutter_quill flutter_quill_extensions
flutter run

### Expected results

Working correct

### Actual results

First it compiles. It produces a bunch of errors and starts on the phone, but in the end it just hangs on a black screen and rebooting doesn’t help

### Console output
![image](https://github.com/singerdmx/flutter-quill/assets/41395688/44955725-3f5d-4c64-bbd0-2a13655942f6)
![image](https://github.com/singerdmx/flutter-quill/assets/41395688/bfe26055-2004-4b08-8ac0-884a0ec6e2d5)

### Flutter version
![image](https://github.com/singerdmx/flutter-quill/assets/41395688/89ebff00-c656-4015-bad7-4eaf29e1a000)

### Same problem
https://github.com/dart-lang/build/issues/3622
https://github.com/flutter/flutter/issues/139925

### Code sample

<details><summary>[Code] main.dart</summary>

``` dart 
// [main.dart]
import 'package:flutter/material.dart';
import 'package:flutter_quill/extensions.dart';
import 'package:flutter_quill/flutter_quill.dart';
import 'package:flutter_quill_extensions/embeds/widgets/image.dart';
import 'package:flutter_quill_extensions/flutter_quill_extensions.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  late final QuillController _controller;
  final _focusNode = FocusNode();
  final _scrollController = ScrollController();

  @override
  void initState() {
    super.initState();

    const content = [
      {
        "insert": "Hello World!\n",
      }
    ];

    _controller = QuillController(
      document: Document.fromJson(content),
      selection: const TextSelection.collapsed(offset: 0),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
          child: QuillEditor(
              configurations: QuillEditorConfigurations(
                  controller: _controller,
                  scrollable: false,
                  readOnly: false,
                  embedBuilders: (isWeb()
                      ? FlutterQuillEmbeds.editorWebBuilders()
                      : FlutterQuillEmbeds.editorBuilders(
                          imageEmbedConfigurations:
                              QuillEditorImageEmbedConfigurations(
                            imageErrorWidgetBuilder:
                                (context, error, stackTrace) {
                              return Text(
                                'Error while loading an image: ${error.toString()}',
                              );
                            },
                            imageProviderBuilder: (context, url) {
                              if (isAndroid(supportWeb: false) ||
                                  isIOS(supportWeb: false) ||
                                  isWeb()) {
                                if (isHttpBasedUrl(url)) {
                                  return NetworkImage(url);
                                }
                              }
                              return getImageProviderByImageSource(
                                url,
                                imageProviderBuilder: null,
                                context: context,
                                assetsPrefix:
                                    QuillSharedExtensionsConfigurations.get(
                                            context: context)
                                        .assetsPrefix,
                              );
                            },
                          ),
                        ))),
              focusNode: _focusNode,
              scrollController: _scrollController)),
    );
  }
}

```

</details>

### Logs

<details><summary>Full text console output</summary>

```console
Launching lib\main.dart on M2103K19PG in debug mode...
���⥬� �� 㤠���� ���� 㪠����� ����.
���⥬� �� 㤠���� ���� 㪠����� ����.
�� 㤠���� ���� 㪠����� 䠩�.
�� 㤠���� ���� 㪠����� 䠩�.
Cannot operate on packages inside the cache.
Compiling bin/build_tool_runner.dart to kernel file bin/build_tool_runner.dill.
Error: Couldn't resolve the package 'build_tool' in 'package:build_tool/build_tool.dart'.
bin/build_tool_runner.dart:1:8: Error: Not found: 'package:build_tool/build_tool.dart'
import 'package:build_tool/build_tool.dart' as build_tool;
       ^
bin/build_tool_runner.dart:3:15: Error: Method not found: 'runMain'.
   build_tool.runMain(args);
              ^^^^^^^
Could not find a command named "bin\build_tool_runner.dill".

Usage: dart <command|dart-file> [arguments]

Global options:
-v, --verbose               Show additional command output.
    --version               Print the Dart SDK version.
    --enable-analytics      Enable analytics.
    --disable-analytics     Disable analytics.
    --suppress-analytics    Disallow analytics for this `dart *` run without changing the analytics configuration.
-h, --help                  Print this usage information.

Available commands:
  analyze    Analyze Dart code in a directory.
  compile    Compile Dart to various formats.
  create     Create a new Dart project.
  devtools   Open DevTools (optionally connecting to an existing application).
  doc        Generate API documentation for Dart projects.
  fix        Apply automated fixes to Dart source code.
  format     Idiomatically format Dart source code.
  info       Show diagnostic information about the installed tooling.
  pub        Work with packages.
  run        Run a Dart program.
  test       Run tests for a project.

Run "dart help <command>" for more information about a command.
See https://dart.dev/tools/dart-tool for detailed documentation.
���⥬� �� 㤠���� ���� 㪠����� ����.
���⥬� �� 㤠���� ���� 㪠����� ����.
�� 㤠���� ���� 㪠����� 䠩�.
�� 㤠���� ���� 㪠����� 䠩�.
Cannot operate on packages inside the cache.
Compiling bin/build_tool_runner.dart to kernel file bin/build_tool_runner.dill.
Error: Couldn't resolve the package 'build_tool' in 'package:build_tool/build_tool.dart'.
bin/build_tool_runner.dart:1:8: Error: Not found: 'package:build_tool/build_tool.dart'
import 'package:build_tool/build_tool.dart' as build_tool;
       ^
bin/build_tool_runner.dart:3:15: Error: Method not found: 'runMain'.
   build_tool.runMain(args);
              ^^^^^^^
Could not find a command named "bin\build_tool_runner.dill".

Usage: dart <command|dart-file> [arguments]

Global options:
-v, --verbose               Show additional command output.
    --version               Print the Dart SDK version.
    --enable-analytics      Enable analytics.
    --disable-analytics     Disable analytics.
    --suppress-analytics    Disallow analytics for this `dart *` run without changing the analytics configuration.
-h, --help                  Print this usage information.

Available commands:
  analyze    Analyze Dart code in a directory.
  compile    Compile Dart to various formats.
  create     Create a new Dart project.
  devtools   Open DevTools (optionally connecting to an existing application).
  doc        Generate API documentation for Dart projects.
  fix        Apply automated fixes to Dart source code.
  format     Idiomatically format Dart source code.
  info       Show diagnostic information about the installed tooling.
  pub        Work with packages.
  run        Run a Dart program.
  test       Run tests for a project.

Run "dart help <command>" for more information about a command.
See https://dart.dev/tools/dart-tool for detailed documentation.
Running Gradle task 'assembleDebug'...                             20,2s
√  Built build\app\outputs\flutter-apk\app-debug.apk.
Syncing files to device M2103K19PG...                              234ms
```

</details>

**Comment by ellet0** [comment]
The issue is not happening in the example, can you check your Android environment?

**Comment by 4ikosa** [comment]
What exactly should I check there?

**Comment by salba360496** [comment]
it is caused by [super_clipboard](https://pub.dev/packages/super_clipboard), used in flutter_quill as dependancy because it used [super_native_extensions](https://pub.dev/packages/super_native_extensions) which used [irondash_engine_context](https://pub.dev/packages/irondash_engine_context), [irondash_message_chann](https://pub.dev/packages/irondash_message_channel).

Solutions: Currently flutter clean and rebuild again.

**Comment by SM-SHIFAT** [comment]
Facing this same issue. Any solve yet?

**Comment by 4ikosa** [comment]
> Solutions: Currently flutter clean and rebuild again.

This didn't help either.  I’ve already done this 5 times in a row and install different old versions

**Comment by salba360496** [comment]
use dart pub cache repair commands to fix pub cache problems. Furthermore, If you try to downgrade to older versions make sure to remove the caret sign (^) from the start of the version numbers otherwise it will install the newest version. Then flutter clean and build again. Hope it will solve your problem.

**Comment by hcanyz** [comment]
+1, Neither ```flutter pub cache clean``` nor  ```flutter clean``` can solve the problem

**Comment by SM-SHIFAT** [comment]
Still facing this in ^9.*.* versions, so I downgraded to last ^8.*.*.

**Comment by salba360496** [comment]
make sure to remove the caret sign (^) from the start of the version numbers otherwise, it will install the newest version. i.e instead of ^8.#.# use only 8.#.#.

**Comment by maksim555659** [comment]
Same issue even on lastest [9.2.2](https://pub.dev/packages/flutter_quill/versions/9.2.2), downgraded to [8.6.4](https://pub.dev/packages/flutter_quill/versions/8.6.4)

**Comment by ellet0** [comment]
Can you create the issue on the super_clipboard plugin repository? It probably a issue from the plugin itself

**Comment by 2426232528** [comment]
> Can you create the issue on the super_clipboard plugin repository? It probably a issue from the plugin itself

I think is not caused by other plugin. I run the example [Repository (GitHub)](https://github.com/singerdmx/flutter-quill/) and report:

`Error: Couldn't resolve the package 'build_tool' in 'package:build_tool/build_tool.dart'.
bin/build_tool_runner.dart:1:8: Error: Not found: 'package:build_tool/build_tool.dart'
import 'package:build_tool/build_tool.dart' as build_tool;
       ^
bin/build_tool_runner.dart:3:15: Error: Method not found: 'runMain'.
   build_tool.runMain(args);
              ^^^^^^^
Could not find a command named "bin\build_tool_runner.dill".`

**Comment by EgorK0rshun** [comment]
any updates?

**Comment by EgorK0rshun** [comment]
temporary solution: 
Add `ndkVersion` in build.gradle
<img width="449" alt="Снимок экрана 2024-01-08 в 14 11 09" src="https://github.com/singerdmx/flutter-quill/assets/120365747/c8464de8-6330-4c6e-9e89-d47a9dde0bd0">

https://developer.android.com/ndk



But this is the wrong way! These kinds of dependencies must be specified inside the library.

**Comment by rahmanrezaee** [comment]
Same issue

**Comment by devx-ubiquity** [comment]
Same problem here . Forced to downgrade to 8.6.4

**Comment by ellet0** [comment]
We have two solutions, either we contact with the author of [https://pub.dev/packages/super_clipboard](super_clipboard)

Or we replace it with another clipboard plugin

that can:
1. retrieve html content from the clipboard
2. Up to date with flutter 3.16 and future versions
3. Can get an image from clipboard or copy image to the clipboard using base 64

Or you can upgrade your ndk version

**Comment by EgorK0rshun** [comment]
> Also make sure to follow the [instructions](https://pub.dev/packages/super_clipboard#getting-started) on the plugin README

Maybe you can add the necessary line from the readmi inside the library? It seems to me that it is wrong that every user who uses `flutter_quill` should register an `ndk` for themselves.

Smth like [this ](https://github.com/singerdmx/flutter-quill/issues/1655#issuecomment-1880811164). 


I also have this problem after increasing version, reason:
<img width="347" alt="Снимок экрана 2024-01-08 в 13 10 53" src="https://github.com/singerdmx/flutter-quill/assets/120365747/b4e42a17-6914-49ca-908c-c8279ff28b5c">
<img width="676" alt="Снимок экрана 2024-01-09 в 21 32 44" src="https://github.com/singerdmx/flutter-quill/assets/120365747/69e5a293-0424-44df-85e1-d97079fec031">

**Comment by ellet0** [comment]
> > Also make sure to follow the [instructions](https://pub.dev/packages/super_clipboard#getting-started) on the plugin README
> 
> Maybe you can add the necessary line from the readmi inside the library? It seems to me that it is wrong that every user who uses `flutter_quill` should register an `ndk` for themselves.
> 
> Smth like [this ](https://github.com/singerdmx/flutter-quill/issues/1655#issuecomment-1880811164). 
> 
> 
> I also had this problem after increasing version, reason:
> <img width="347" alt="Снимок экрана 2024-01-08 в 13 10 53" src="https://github.com/singerdmx/flutter-quill/assets/120365747/b4e42a17-6914-49ca-908c-c8279ff28b5c">
> <img width="676" alt="Снимок экрана 2024-01-09 в 21 32 44" src="https://github.com/singerdmx/flutter-quill/assets/120365747/69e5a293-0424-44df-85e1-d97079fec031">
> 
> and after an explicit indication version of local `ndk` in the `build.gragle` it worked.

This is a package, not a plugin. Besides, we can't change the minimum version because it will require the user to change it anyway

Please make sure to follow the instructions and install rust on Windows

I need to know which platform you are using

**Comment by ellet0** [comment]
Can you try 9.2.5? It doesn't contain any fix for the issue, but the new version of the super clipboard has more error messages and we neer it to debug the bug

**Comment by ellet0** [comment]
> > Also make sure to follow the [instructions](https://pub.dev/packages/super_clipboard#getting-started) on the plugin README
> 
> Maybe you can add the necessary line from the readmi inside the library? It seems to me that it is wrong that every user who uses `flutter_quill` should register an `ndk` for themselves.
> 
> Smth like [this ](https://github.com/singerdmx/flutter-quill/issues/1655#issuecomment-1880811164). 
> 
> 
> I also had this problem after increasing version, reason:
> <img width="347" alt="Снимок экрана 2024-01-08 в 13 10 53" src="https://github.com/singerdmx/flutter-quill/assets/120365747/b4e42a17-6914-49ca-908c-c8279ff28b5c">
> <img width="676" alt="Снимок экрана 2024-01-09 в 21 32 44" src="https://github.com/singerdmx/flutter-quill/assets/120365747/69e5a293-0424-44df-85e1-d97079fec031">
> 
> and after an explicit indication version of local `ndk` in the `build.gragle` it worked.

May I ask when you created your flutter project? Because all new flutter projects has ndk version a default

**Comment by mox1206** [comment]
INFO: Precompiled binaries are disabled
INFO: Installing Rust toolchain: nightly
INFO: Installing Rust target: armv7-linux-androideabi
INFO: Building super_native_extensions for armv7-linux-androideabi
INFO: Installing NDK 23.1.7779620
SEVERE: ================================================================================
SEVERE: Cargokit BuildTool failed with error:
SEVERE: --------------------------------------------------------------------------------
SEVERE: ProcessException: 系统找不到指定的文件�?
SEVERE: 
SEVERE:   Command: %ANDROID_SDK_PATH%\sdk\cmdline-tools\latest\bin\sdkmanager.bat --install ndk;23.1.7779620
SEVERE: --------------------------------------------------------------------------------
SEVERE: #0      _ProcessImpl._runAndWait (dart:io-patch/process_patch.dart:488:7)
SEVERE: #1      _runNonInteractiveProcessSync (dart:io-patch/process_patch.dart:633:18)
SEVERE: #2      Process.runSync (dart:io-patch/process_patch.dart:68:12)
SEVERE: #3      runCommand (package:build_tool/src/util.dart:107:23)
SEVERE: #4      AndroidEnvironment.installNdk (package:build_tool/src/android_environment.dart:73:5)
SEVERE: #5      RustBuilder._buildEnvironment (package:build_tool/src/builder.dart:190:13)
SEVERE: #6      RustBuilder.build (package:build_tool/src/builder.dart:157:26)
SEVERE: #7      ArtifactProvider.getArtifacts (package:build_tool/src/artifacts_provider.dart:68:39)
SEVERE: <asynchronous suspension>
SEVERE: #8      BuildGradle.build (package:build_tool/src/build_gradle.dart:32:23)
SEVERE: <asynchronous suspension>
SEVERE: #9      BuildGradleCommand.runBuildCommand (package:build_tool/src/build_tool.dart:62:5)
SEVERE: <asynchronous suspension>
SEVERE: #10     BuildCommand.run (package:build_tool/src/build_tool.dart:34:5)
SEVERE: <asynchronous suspension>
SEVERE: #11     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
SEVERE: <asynchronous suspension>
SEVERE: #12     runMain (package:build_tool/src/build_tool.dart:248:5)
SEVERE: <asynchronous suspension>
SEVERE: --------------------------------------------------------------------------------
SEVERE: BuildTool arguments: [build-gradle]
SEVERE: ================================================================================
ϵͳ�Ҳ���ָ����·����
ϵͳ�Ҳ���ָ����·����
ϵͳ�Ҳ���ָ�����ļ���
ϵͳ�Ҳ���ָ�����ļ���
Cannot operate on packages inside the cache.

I got an error when using 9.2.5. Only the 9.0 directory can be found locally, and there is no latest directory.
%ANDROID_SDK_PATH%\sdk\cmdline-tools\9.0

**Comment by ellet0** [comment]
You can try out with `9.2.6`

**Comment by mox1206** [comment]
After using 9.2.6, irondash_engine_context can be built normally, but super_native_extensions still fails. The error is as follows
![无标题2](https://github.com/singerdmx/flutter-quill/assets/8570048/5ab4836e-13f9-4eff-9b4d-345470289048)
Run flutter build apk -v log as follows
[log.txt](https://github.com/singerdmx/flutter-quill/files/13961702/log.txt)

My English is not good, this is from Google Translate, I don’t know if you can understand it.

**Comment by mox1206** [comment]
After using 9.2.6, irondash_engine_context can be built normally, but super_native_extensions will still fail to build, with the following error
![无标题2](https://github.com/singerdmx/flutter-quill/assets/8570048/13ae762b-41bd-47bc-af08-23b0518e15d9)
The log of running flutter build apk -v is as follows
[log.txt](https://github.com/singerdmx/flutter-quill/files/13961839/log.txt)

**Comment by knopp** [comment]
Can you try installing https://visualstudio.microsoft.com/visual-cpp-build-tools/ ?

It seems that you have Rustup installed, which requires the build tools to work properly on windows Another alternative would be to uninstall Rustup, in which case the plugin will just use prebuilt binaries.

**Comment by ellet0** [comment]
> Can you try installing https://visualstudio.microsoft.com/visual-cpp-build-tools/ ?
> 
> It seems that you have Rustup installed, which requires the build tools to work properly on windows Another alternative would be to uninstall Rustup, in which case the plugin will just use prebuilt binaries.

Make sense.

**Comment by mox1206** [comment]
> Can you try installing https://visualstudio.microsoft.com/visual-cpp-build-tools/ ?
> 
> It seems that you have Rustup installed, which requires the build tools to work properly on windows Another alternative would be to uninstall Rustup, in which case the plugin will just use prebuilt binaries.

Thank you very much, I can build normally after uninstalling rust.

**Comment by ellet0** [comment]
I'm closing this issue as fixed as @knopp fixed it to all the users of `super_clipboard` and `flutter_quill`

If anyone still facing it please let me know

**Comment by MickaelHrndz** [comment]
To fix the error with "irondash_engine_context", I had to add the missing `ndkVersion flutter.ndkVersion` line after `compileSdkVersion flutter.compileSdkVersion` in `android/app/build.gradle`

**Comment by knopp** [comment]
> To fix the error with "irondash_engine_context", I had to add the missing `ndkVersion flutter.ndkVersion` line after `compileSdkVersion flutter.compileSdkVersion` in `android/app/build.gradle`

That should already be there for any new Flutter generated projects.
