### ISSUE TITLE
Localizations Delegate Issue

### ISSUE THREAD

**Issue by tauqeerkhattak** [singerdmx/flutter-quill#1699]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

9.2.6

### Steps to reproduce

1. Add swedish support to app using flutter_localizations library
2. Add flutter_quill to flutter app
3. Install app in emulator and the errors are thrown.

### Expected results

App runs as expected.

### Actual results

The following warning appears after adding FlutterQuillLocalizations.delegate to localizationDelegates:

Warning: This application's locale, sv, is not supported by all of its localization delegates.

And on loading page using QuillEditor, the fullowing exception is thrown: 

The instance of FlutterQuillLocalizations.of(context) is null and it's required, please make sure you wrapping the current widget with FlutterQuillLocalizationsWidget or add FlutterQuillLocalizations.delegate to the localizationsDelegates in your App widget, please consider report this in GitHub as a bug

### Code sample

<details><summary>Code sample</summary>

```dart
Column(
  children: [
    QuillToolbar.simple(
      configurations: QuillSimpleToolbarConfigurations(
        controller: _controller,
      ),
    ),
    Expanded(
      child: QuillEditor.basic(
        configurations: QuillEditorConfigurations(
          controller: _controller,
          padding: const EdgeInsets.all(20),
          readOnly: false,
        ),
      ),
    ),
  ],
),
```

</details>

### Logs

<details><summary>Logs</summary>

```console
======== Exception caught by widgets library =======================================================
The following UnimplementedError was thrown building QuillToolbarHistoryButton(dirty, dependencies: [QuillSimpleToolbarProvider, _LocalizationsScope-[GlobalKey#2328c]], state: QuillToolbarHistoryButtonState#18bdd):
The instance of FlutterQuillLocalizations.of(context) is null and it's required, please make sure you wrapping the current widget with FlutterQuillLocalizationsWidget or add FlutterQuillLocalizations.delegate to the localizationsDelegates in your App widget, please consider report this in GitHub as a bug

The relevant error-causing widget was: 
  Column Column:file:///D:/StudioProjects/organaise_app/lib/ui/pages/reminder/add_reminder_page.dart:31:16
When the exception was thrown, this was the stack: 
#0      LocalizationsExt.loc (package:flutter_quill/src/l10n/extensions/localizations.dart:13:10)
#1      QuillToolbarHistoryButtonState.build (package:flutter_quill/src/widgets/toolbar/buttons/history_button.dart:60:34)
#2      StatefulElement.build (package:flutter/src/widgets/framework.dart:5583:27)
#3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5471:15)
#4      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634:11)
#5      Element.rebuild (package:flutter/src/widgets/framework.dart:5187:7)
#6      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453:5)
#7      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5625:11)
#8      ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447:5)
#9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326:16)
#10     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6871:36)
#11     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6883:32)
...     Normal element mounting (60 frames)
#71     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326:16)
#72     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6871:36)
#73     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6883:32)
...     Normal element mounting (40 frames)
#113    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326:16)
#114    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6871:36)
#115    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6883:32)
...     Normal element mounting (136 frames)
#251    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326:16)
#252    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6871:36)
#253    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6883:32)
...     Normal element mounting (178 frames)
#431    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326:16)
#432    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6871:36)
#433    Element.updateChild (package:flutter/src/widgets/framework.dart:3837:18)
#434    Element.updateChildren (package:flutter/src/widgets/framework.dart:4024:32)
#435    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6896:17)
#436    Element.updateChild (package:flutter/src/widgets/framework.dart:3815:15)
#437    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496:16)
#438    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634:11)
#439    Element.rebuild (package:flutter/src/widgets/framework.dart:5187:7)
#440    StatefulElement.update (package:flutter/src/widgets/framework.dart:5657:5)
#441    Element.updateChild (package:flutter/src/widgets/framework.dart:3815:15)
#442    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496:16)
#443    Element.rebuild (package:flutter/src/widgets/framework.dart:5187:7)
#444    ProxyElement.update (package:flutter/src/widgets/framework.dart:5800:5)
#445    Element.updateChild (package:flutter/src/widgets/framework.dart:3815:15)
#446    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496:16)
#447    Element.rebuild (package:flutter/src/widgets/framework.dart:5187:7)
#448    ProxyElement.update (package:flutter/src/widgets/framework.dart:5800:5)
#449    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:105:11)
#450    Element.updateChild (package:flutter/src/widgets/framework.dart:3815:15)
#451    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496:16)
#452    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634:11)
#453    Element.rebuild (package:flutter/src/widgets/framework.dart:5187:7)
#454    StatefulElement.update (package:flutter/src/widgets/framework.dart:5657:5)
#455    Element.updateChild (package:flutter/src/widgets/framework.dart:3815:15)
#456    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496:16)
#457    Element.rebuild (package:flutter/src/widgets/framework.dart:5187:7)
#458    ProxyElement.update (package:flutter/src/widgets/framework.dart:5800:5)
#459    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:105:11)
#460    Element.updateChild (package:flutter/src/widgets/framework.dart:3815:15)
#461    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496:16)
#462    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634:11)
#463    Element.rebuild (package:flutter/src/widgets/framework.dart:5187:7)
#464    StatefulElement.update (package:flutter/src/widgets/framework.dart:5657:5)
#465    Element.updateChild (package:flutter/src/widgets/framework.dart:3815:15)
#466    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496:16)
#467    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634:11)
#468    Element.rebuild (package:flutter/src/widgets/framework.dart:5187:7)
#469    StatefulElement.update (package:flutter/src/widgets/framework.dart:5657:5)
#470    Element.updateChild (package:flutter/src/widgets/framework.dart:3815:15)
#471    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6743:14)
#472    Element.updateChild (package:flutter/src/widgets/framework.dart:3815:15)
#473    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6743:14)
#474    Element.updateChild (package:flutter/src/widgets/framework.dart:3815:15)
#475    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496:16)
#476    Element.rebuild (package:flutter/src/widgets/framework.dart:5187:7)
#477    ProxyElement.update (package:flutter/src/widgets/framework.dart:5800:5)
#478    Element.updateChild (package:flutter/src/widgets/framework.dart:3815:15)
#479    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496:16)
#480    Element.rebuild (package:flutter/src/widgets/framework.dart:5187:7)
#481    ProxyElement.update (package:flutter/src/widgets/framework.dart:5800:5)
#482    Element.updateChild (package:flutter/src/widgets/framework.dart:3815:15)
#483    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496:16)
#484    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634:11)
#485    Element.rebuild (package:flutter/src/widgets/framework.dart:5187:7)
#486    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2895:19)
#487    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:984:21)
#488    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:457:5)
#489    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1325:15)
#490    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1255:9)
#491    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1113:5)
#495    _invoke (dart:ui/hooks.dart:314:10)
#496    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:383:5)
#497    _drawFrame (dart:ui/hooks.dart:283:31)
(elided 3 frames from dart:async)
====================================================================================================

======== Exception caught by widgets library =======================================================
The following UnimplementedError was thrown building QuillToolbarHistoryButton(dirty, dependencies: [QuillSimpleToolbarProvider, _LocalizationsScope-[GlobalKey#2328c]], state: QuillToolbarHistoryButtonState#e91a8):
The instance of FlutterQuillLocalizations.of(context) is null and it's required, please make sure you wrapping the current widget with FlutterQuillLocalizationsWidget or add FlutterQuillLocalizations.delegate to the localizationsDelegates in your App widget, please consider report this in GitHub as a bug

The relevant error-causing widget was: 
  Column Column:file:///D:/StudioProjects/organaise_app/lib/ui/pages/reminder/add_reminder_page.dart:31:16
When the exception was thrown, this was the stack: 
#0      LocalizationsExt.loc (package:flutter_quill/src/l10n/extensions/localizations.dart:13:10)
#1      QuillToolbarHistoryButtonState.build (package:flutter_quill/src/widgets/toolbar/buttons/history_button.dart:60:53)
#2      StatefulElement.build (package:flutter/src/widgets/framework.dart:5583:27)
#3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5471:15)
#4      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634:11)
#5      Element.rebuild (package:flutter/src/widgets/framework.dart:5187:7)
#6      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453:5)
#7      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5625:11)
#8      ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447:5)
#9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326:16)
#10     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6871:36)
#11     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6883:32)
...     Normal element mounting (60 frames)
#71     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326:16)
#72     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6871:36)
#73     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6883:32)
...     Normal element mounting (40 frames)
#113    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326:16)
#114    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6871:36)
#115    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6883:32)
...     Normal element mounting (136 frames)
#251    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326:16)
#252    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6871:36)
#253    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6883:32)
...     Normal element mounting (178 frames)
#431    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326:16)
#432    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6871:36)
#433    Element.updateChild (package:flutter/src/widgets/framework.dart:3837:18)
#434    Element.updateChildren (package:flutter/src/widgets/framework.dart:4024:32)
#435    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6896:17)
#436    Element.updateChild (package:flutter/src/widgets/framework.dart:3815:15)
#437    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496:16)
#438    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634:11)
#439    Element.rebuild (package:flutter/src/widgets/framework.dart:5187:7)
#440    StatefulElement.update (package:flutter/src/widgets/framework.dart:5657:5)
#441    Element.updateChild (package:flutter/src/widgets/framework.dart:3815:15)
#442    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496:16)
#443    Element.rebuild (package:flutter/src/widgets/framework.dart:5187:7)
#444    ProxyElement.update (package:flutter/src/widgets/framework.dart:5800:5)
#445    Element.updateChild (package:flutter/src/widgets/framework.dart:3815:15)
#446    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496:16)
#447    Element.rebuild (package:flutter/src/widgets/framework.dart:5187:7)
#448    ProxyElement.update (package:flutter/src/widgets/framework.dart:5800:5)
#449    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:105:11)
#450    Element.updateChild (package:flutter/src/widgets/framework.dart:3815:15)
#451    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496:16)
#452    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634:11)
#453    Element.rebuild (package:flutter/src/widgets/framework.dart:5187:7)
#454    StatefulElement.update (package:flutter/src/widgets/framework.dart:5657:5)
#455    Element.updateChild (package:flutter/src/widgets/framework.dart:3815:15)
#456    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496:16)
#457    Element.rebuild (package:flutter/src/widgets/framework.dart:5187:7)
#458    ProxyElement.update (package:flutter/src/widgets/framework.dart:5800:5)
#459    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:105:11)
#460    Element.updateChild (package:flutter/src/widgets/framework.dart:3815:15)
#461    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496:16)
#462    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634:11)
#463    Element.rebuild (package:flutter/src/widgets/framework.dart:5187:7)
#464    StatefulElement.update (package:flutter/src/widgets/framework.dart:5657:5)
#465    Element.updateChild (package:flutter/src/widgets/framework.dart:3815:15)
#466    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496:16)
#467    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634:11)
#468    Element.rebuild (package:flutter/src/widgets/framework.dart:5187:7)
#469    StatefulElement.update (package:flutter/src/widgets/framework.dart:5657:5)
#470    Element.updateChild (package:flutter/src/widgets/framework.dart:3815:15)
#471    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6743:14)
#472    Element.updateChild (package:flutter/src/widgets/framework.dart:3815:15)
#473    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6743:14)
#474    Element.updateChild (package:flutter/src/widgets/framework.dart:3815:15)
#475    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496:16)
#476    Element.rebuild (package:flutter/src/widgets/framework.dart:5187:7)
#477    ProxyElement.update (package:flutter/src/widgets/framework.dart:5800:5)
#478    Element.updateChild (package:flutter/src/widgets/framework.dart:3815:15)
#479    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496:16)
#480    Element.rebuild (package:flutter/src/widgets/framework.dart:5187:7)
#481    ProxyElement.update (package:flutter/src/widgets/framework.dart:5800:5)
#482    Element.updateChild (package:flutter/src/widgets/framework.dart:3815:15)
#483    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496:16)
#484    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634:11)
#485    Element.rebuild (package:flutter/src/widgets/framework.dart:5187:7)
#486    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2895:19)
#487    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:984:21)
#488    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:457:5)
#489    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1325:15)
#490    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1255:9)
#491    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1113:5)
#495    _invoke (dart:ui/hooks.dart:314:10)
#496    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:383:5)
#497    _drawFrame (dart:ui/hooks.dart:283:31)
(elided 3 frames from dart:async)
====================================================================================================

======== Exception caught by widgets library =======================================================
The following UnimplementedError was thrown building Builder(dependencies: [QuillSimpleToolbarProvider]):
The instance of FlutterQuillLocalizations.of(context) is null and it's required, please make sure you wrapping the current widget with FlutterQuillLocalizationsWidget or add FlutterQuillLocalizations.delegate to the localizationsDelegates in your App widget, please consider report this in GitHub as a bug

The relevant error-causing widget was: 
  Column Column:file:///D:/StudioProjects/organaise_app/lib/ui/pages/reminder/add_reminder_page.dart:31:16
When the exception was thrown, this was the stack: 
#0      LocalizationsExt.loc (package:flutter_quill/src/l10n/extensions/localizations.dart:13:10)
#1      QuillToolbarFontFamilyButtonState._defaultDisplayText (package:flutter_quill/src/widgets/toolbar/buttons/font_family_button.dart:62:17)
#2      QuillToolbarFontFamilyButtonState.didChangeDependencies (package:flutter_quill/src/widgets/toolbar/buttons/font_family_button.dart:55:21)
#3      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5620:11)
#4      ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447:5)
#5      Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326:16)
#6      MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6871:36)
#7      MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6883:32)
...     Normal element mounting (60 frames)
#67     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326:16)
#68     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6871:36)
#69     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6883:32)
...     Normal element mounting (40 frames)
#109    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326:16)
#110    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6871:36)
#111    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6883:32)
...     Normal element mounting (136 frames)
#247    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326:16)
#248    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6871:36)
#249    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6883:32)
...     Normal element mounting (178 frames)
#427    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326:16)
#428    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6871:36)
#429    Element.updateChild (package:flutter/src/widgets/framework.dart:3837:18)
#430    Element.updateChildren (package:flutter/src/widgets/framework.dart:4024:32)
#431    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6896:17)
#432    Element.updateChild (package:flutter/src/widgets/framework.dart:3815:15)
#433    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496:16)
#434    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634:11)
#435    Element.rebuild (package:flutter/src/widgets/framework.dart:5187:7)
#436    StatefulElement.update (package:flutter/src/widgets/framework.dart:5657:5)
#437    Element.updateChild (package:flutter/src/widgets/framework.dart:3815:15)
#438    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496:16)
#439    Element.rebuild (package:flutter/src/widgets/framework.dart:5187:7)
#440    ProxyElement.update (package:flutter/src/widgets/framework.dart:5800:5)
#441    Element.updateChild (package:flutter/src/widgets/framework.dart:3815:15)
#442    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496:16)
#443    Element.rebuild (package:flutter/src/widgets/framework.dart:5187:7)
#444    ProxyElement.update (package:flutter/src/widgets/framework.dart:5800:5)
#445    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:105:11)
#446    Element.updateChild (package:flutter/src/widgets/framework.dart:3815:15)
#447    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496:16)
#448    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634:11)
#449    Element.rebuild (package:flutter/src/widgets/framework.dart:5187:7)
#450    StatefulElement.update (package:flutter/src/widgets/framework.dart:5657:5)
#451    Element.updateChild (package:flutter/src/widgets/framework.dart:3815:15)
#452    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496:16)
#453    Element.rebuild (package:flutter/src/widgets/framework.dart:5187:7)
#454    ProxyElement.update (package:flutter/src/widgets/framework.dart:5800:5)
#455    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:105:11)
#456    Element.updateChild (package:flutter/src/widgets/framework.dart:3815:15)
#457    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496:16)
#458    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634:11)
#459    Element.rebuild (package:flutter/src/widgets/framework.dart:5187:7)
#460    StatefulElement.update (package:flutter/src/widgets/framework.dart:5657:5)
#461    Element.updateChild (package:flutter/src/widgets/framework.dart:3815:15)
#462    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496:16)
#463    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634:11)
#464    Element.rebuild (package:flutter/src/widgets/framework.dart:5187:7)
#465    StatefulElement.update (package:flutter/src/widgets/framework.dart:5657:5)
#466    Element.updateChild (package:flutter/src/widgets/framework.dart:3815:15)
#467    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6743:14)
#468    Element.updateChild (package:flutter/src/widgets/framework.dart:3815:15)
#469    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6743:14)
#470    Element.updateChild (package:flutter/src/widgets/framework.dart:3815:15)
#471    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496:16)
#472    Element.rebuild (package:flutter/src/widgets/framework.dart:5187:7)
#473    ProxyElement.update (package:flutter/src/widgets/framework.dart:5800:5)
#474    Element.updateChild (package:flutter/src/widgets/framework.dart:3815:15)
#475    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496:16)
#476    Element.rebuild (package:flutter/src/widgets/framework.dart:5187:7)
#477    ProxyElement.update (package:flutter/src/widgets/framework.dart:5800:5)
#478    Element.updateChild (package:flutter/src/widgets/framework.dart:3815:15)
#479    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496:16)
#480    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634:11)
#481    Element.rebuild (package:flutter/src/widgets/framework.dart:5187:7)
#482    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2895:19)
#483    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:984:21)
#484    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:457:5)
#485    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1325:15)
#486    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1255:9)
#487    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1113:5)
#491    _invoke (dart:ui/hooks.dart:314:10)
#492    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:383:5)
#493    _drawFrame (dart:ui/hooks.dart:283:31)
(elided 3 frames from dart:async)
====================================================================================================
```

</details>

**Comment by silkyland** [comment]
I got same problem using `th` language are not in list as supported language.

**Comment by EchoEllet** [comment]
Please try with the latest version, this should be no longer an issue.
