### ISSUE TITLE
Error (Xcode): could not compile `super_native_extensions` (lib) due to 58 previous errors

### ISSUE THREAD

**Issue by Jaxiii** [singerdmx/flutter-quill#1712]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

9.2.10

### Steps to reproduce

1. Install any version using super_native_extensions (dependecy of super_clipboard: ^0.8.4)
2. Try to run on iOS 16.2

### Expected results

Apple should compile

### Actual results

Error (Xcode): could not compile `super_native_extensions` (lib) due to 58 previous errors
/Users/~/ios/Pods/SEVERE:0:0

Could not build the application for the simulator.
Error launching application on iPhone 14 Pro Max.

### Code sample

<details><summary>Code sample</summary>

```dart
...
dependencies:
  flutter:
    sdk: flutter
  flutter_quill: ^9.2.10
...
```

```dart
QuillEditor.basic(
  configurations: QuillEditorConfigurations(
    readOnly: true,
    showCursor: false,
    controller: QuillController(
      document: Document(),
      selection: const TextSelection(
        baseOffset: 0,
        extentOffset: 0,
      ),
    ),
  ),
),
```
</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[  +22 ms] Failed to build iOS app
[        ] Error (Xcode): could not compile `super_native_extensions` (lib) due to 58 previous errors
           /Users/~/ios/Pods/SEVERE:0:0
           
[   +1 ms] Could not build the application for the simulator.
[        ] Error launching application on iPhone 14 Pro Max.
[   +1 ms] "flutter run" took 43.335ms.
[   +1 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:790:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1367:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:348:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:294:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:112:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>
           
           
[ +240 ms] ensureAnalyticsSent: 239ms
[        ] Running 1 shutdown hook
[  +17 ms] Shutdown hooks complete
[        ] exiting with code 1
```

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.9, on macOS 12.5 21G72 darwin-arm64, locale pt-BR)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.85.1)
[✓] Connected device (2 available)
[✓] Network resources

• No issues found!
```
</details>

**Comment by Jaxiii** [comment]
Solution is here https://github.com/superlistapp/super_native_extensions/issues/279,
But I would recommend to mention that an up to date version of Rust is required for this package, since the bellow is not fully correct, and others may encounter this error.

"Platform Specific Configurations 
Before using the package, we must inform you the package use the following plugins:

```
url_launcher
flutter_keyboard_visibility
device_info_plus
super_clipboard
```

All of them doesn't require any platform specific setup, except [super_clipboard](https://pub.dev/packages/super_clipboard) which needs some setup on Android only, it's used to support copying images and pasting them into editor then you must setup it, open the page in pub.dev and read the README.md to get the instructions. 

The minSdkVersion is 23 as super_clipboard requires it "
