### ISSUE TITLE
Could not find the default tooltip for Attribute H1 in Toolbar

### ISSUE THREAD

**Issue by tbusot** [singerdmx/flutter-quill#1867]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

9.3.11

### Steps to reproduce

Create a QuillToolbar and add a `H1` through `H6` ToggleStyleButton to the toolbar (See code sample attached). If you manually set the iconData attribute, you will avoid the error, but neither material nor cupertino icons contains the H1-H6 icons.

```
...
                QuillToolbarToggleStyleButton(
                  controller: quillController,
                  attribute: Attribute.h1,
                  options: QuillToolbarToggleStyleButtonOptions(
                    iconSize: 12.0,
                    tooltip: 'H1',
                    iconTheme: iconTheme,
                  ),
                ),
...
```

### Expected results

Quill Toolbar renders with H1 - H6 as configured.

### Actual results

App crashes with the following error:

```
flutter: caught error => ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞════════════════════════
flutter: The following ArgumentError was thrown building
flutter: QuillToolbarToggleStyleButton(dirty, state:
flutter: QuillToolbarToggleStyleButtonState#2252f):
flutter: Invalid argument(s): Could not find the default tooltip for
flutter: Attribute{key: header, scope: AttributeScope.block, value: 6}
flutter:
flutter: The relevant error-causing widget was:
flutter:   QuillToolbarToggleStyleButton
flutter:   QuillToolbarToggleStyleButton:file:///Users/tbusot/Documents/dev/iloomi/iloomi_app/lib/features/StoryEditor/presentation/components/story_editor_toolbar_sliver.dart:182:17
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      QuillToolbarToggleStyleButtonState._defaultTooltipAndIconData (package:flutter_quill/src/widgets/toolbar/buttons/toggle_style_button.dart:89:9)
flutter: #1      QuillToolbarToggleStyleButtonState.iconData (package:flutter_quill/src/widgets/toolbar/buttons/toggle_style_button.dart:102:9)
flutter: #2      QuillToolbarToggleStyleButtonState.build (package:flutter_quill/src/widgets/toolbar/buttons/toggle_style_button.dart:130:9)
flutter: #3      StatefulElement.build (package:flutter/src/widgets/framework.dart:5592:27)
flutter: #4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5480:15)
flutter: #5      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643:11)
flutter: #6      Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
flutter: #7      StatefulElement.update (package:flutter/src/widgets/framework.dart:5666:5)
flutter: #8      Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
flutter: #9      Element.updateChildren (package:flutter/src/widgets/framework.dart:3973:32)
flutter: #10     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6918:17)
flutter: #11     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
flutter: #12     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6765:14)
flutter: #13     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
flutter: #14     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6765:14)
flutter: #15     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
flutter: #16     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6765:14)
flutter: #17     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)

```

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter_quill/flutter_quill.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Quill Example',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Quill Example'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  QuillController? quillController;

  @override
  Widget build(BuildContext context) {
    quillController ??= QuillController.basic();

    final colorScheme = Theme.of(context).colorScheme;
    final iconTheme = QuillIconTheme(
      iconButtonSelectedData: IconButtonData(
        color: colorScheme.background,
        iconSize: 12.0,
        padding: EdgeInsets.zero,
        style: ButtonStyle(
          backgroundColor: MaterialStateProperty.all(
            colorScheme.onSurface.withOpacity(.75),
          ),
          shape: MaterialStateProperty.all(
            RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(4.0),
            ),
          ),
        ),
        visualDensity: VisualDensity.compact,
      ),
      iconButtonUnselectedData: IconButtonData(
        color: colorScheme.onSurface,
        padding: EdgeInsets.zero,
        visualDensity: VisualDensity.compact,
      ),
    );
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: Stack(
        fit: StackFit.expand,
        children: [
          QuillToolbar(
            configurations: const QuillToolbarConfigurations(
              buttonOptions: QuillSimpleToolbarButtonOptions(
                base: QuillToolbarBaseButtonOptions(),
              ),
            ),
            child: SingleChildScrollView(
              scrollDirection: Axis.horizontal,
              child: Wrap(
                children: [
                  QuillToolbarToggleStyleButton(
                    controller: quillController!,
                    attribute: Attribute.h1,
                    options: QuillToolbarToggleStyleButtonOptions(
                      // iconData: Icons.format_size,
                      iconSize: 12.0,
                      tooltip: 'H1',
                      iconTheme: iconTheme,
                    ),
                  ),
                ],
              ),
            ),
          ),
        ],
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console

════════ Exception caught by widgets library ═══════════════════════════════════
The following ArgumentError was thrown building QuillToolbarToggleStyleButton(dirty, state: QuillToolbarToggleStyleButtonState#ad801):
Invalid argument(s): Could not find the default tooltip for Attribute{key: header, scope: AttributeScope.block, value: 1}

The relevant error-causing widget was:
    QuillToolbarToggleStyleButton QuillToolbarToggleStyleButton:file:///Users/tbusot/Documents/dev/flutter_apps/quill_error_sample/quill_example/lib/main.dart:83:19

When the exception was thrown, this was the stack:
#0      QuillToolbarToggleStyleButtonState._defaultTooltipAndIconData (package:flutter_quill/src/widgets/toolbar/buttons/toggle_style_button.dart:89:9)
#1      QuillToolbarToggleStyleButtonState.iconData (package:flutter_quill/src/widgets/toolbar/buttons/toggle_style_button.dart:102:9)
#2      QuillToolbarToggleStyleButtonState.build (package:flutter_quill/src/widgets/toolbar/buttons/toggle_style_button.dart:130:9)
#3      StatefulElement.build (package:flutter/src/widgets/framework.dart:5592:27)
#4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5480:15)
#5      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643:11)
#6      Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#7      StatefulElement.update (package:flutter/src/widgets/framework.dart:5666:5)
#8      Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#9      Element.updateChildren (package:flutter/src/widgets/framework.dart:3973:32)
#10     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6918:17)
#11     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#12     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6765:14)
#13     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#14     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6765:14)
#15     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#16     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6765:14)
#17     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#18     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6765:14)
#19     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#20     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6765:14)
#21     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#22     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#23     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643:11)
#24     Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#25     StatefulElement.update (package:flutter/src/widgets/framework.dart:5666:5)
#26     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#27     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6765:14)
#28     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#29     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#30     Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#31     ProxyElement.update (package:flutter/src/widgets/framework.dart:5809:5)
#32     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#33     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6765:14)
#34     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#35     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#36     Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#37     ProxyElement.update (package:flutter/src/widgets/framework.dart:5809:5)
#38     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#39     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#40     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643:11)
#41     Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#42     StatefulElement.update (package:flutter/src/widgets/framework.dart:5666:5)
#43     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#44     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#45     Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#46     StatelessElement.update (package:flutter/src/widgets/framework.dart:5556:5)
#47     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#48     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#49     Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#50     ProxyElement.update (package:flutter/src/widgets/framework.dart:5809:5)
#51     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#52     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#53     Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#54     ProxyElement.update (package:flutter/src/widgets/framework.dart:5809:5)
#55     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#56     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#57     Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#58     ProxyElement.update (package:flutter/src/widgets/framework.dart:5809:5)
#59     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#60     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6765:14)
#61     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#62     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#63     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643:11)
#64     Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#65     StatefulElement.update (package:flutter/src/widgets/framework.dart:5666:5)
#66     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#67     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#68     Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#69     StatelessElement.update (package:flutter/src/widgets/framework.dart:5556:5)
#70     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#71     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#72     Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#73     StatelessElement.update (package:flutter/src/widgets/framework.dart:5556:5)
#74     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#75     Element.updateChildren (package:flutter/src/widgets/framework.dart:3973:32)
#76     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6918:17)
#77     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#78     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#79     Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#80     StatelessElement.update (package:flutter/src/widgets/framework.dart:5556:5)
#81     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#82     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#83     Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#84     StatelessElement.update (package:flutter/src/widgets/framework.dart:5556:5)
#85     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#86     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#87     Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#88     ProxyElement.update (package:flutter/src/widgets/framework.dart:5809:5)
#89     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#90     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#91     Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#92     ProxyElement.update (package:flutter/src/widgets/framework.dart:5809:5)
#93     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#94     Element.updateChildren (package:flutter/src/widgets/framework.dart:3973:32)
#95     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6918:17)
#96     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#97     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#98     Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#99     ProxyElement.update (package:flutter/src/widgets/framework.dart:5809:5)
#100    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#101    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#102    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643:11)
#103    Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#104    StatefulElement.update (package:flutter/src/widgets/framework.dart:5666:5)
#105    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#106    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#107    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643:11)
#108    Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#109    StatefulElement.update (package:flutter/src/widgets/framework.dart:5666:5)
#110    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#111    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#112    Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#113    ProxyElement.update (package:flutter/src/widgets/framework.dart:5809:5)
#114    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#115    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#116    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643:11)
#117    Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#118    StatefulElement.update (package:flutter/src/widgets/framework.dart:5666:5)
#119    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#120    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6765:14)
#121    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#122    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#123    Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#124    ProxyElement.update (package:flutter/src/widgets/framework.dart:5809:5)
#125    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#126    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6765:14)
#127    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#128    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#129    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643:11)
#130    Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#131    StatefulElement.update (package:flutter/src/widgets/framework.dart:5666:5)
#132    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#133    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#134    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643:11)
#135    Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#136    StatefulElement.update (package:flutter/src/widgets/framework.dart:5666:5)
#137    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#138    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#139    Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#140    ProxyElement.update (package:flutter/src/widgets/framework.dart:5809:5)
#141    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#142    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#143    Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#144    ProxyElement.update (package:flutter/src/widgets/framework.dart:5809:5)
#145    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#146    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#147    Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#148    ProxyElement.update (package:flutter/src/widgets/framework.dart:5809:5)
#149    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#150    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#151    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643:11)
#152    Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#153    StatefulElement.update (package:flutter/src/widgets/framework.dart:5666:5)
#154    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#155    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#156    Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#157    ProxyElement.update (package:flutter/src/widgets/framework.dart:5809:5)
#158    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#159    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#160    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643:11)
#161    Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#162    StatefulElement.update (package:flutter/src/widgets/framework.dart:5666:5)
#163    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#164    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#165    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643:11)
#166    Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#167    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2904:19)
#168    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:989:21)
#169    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:448:5)
#170    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1386:15)
#171    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1311:9)
#172    SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:1034:7)
#176    _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
(elided 3 frames from class _Timer and dart:async-patch)
════════════════════════════════════════════════════════════════════════════════
Restarted application in 417ms.

```

</details>

**Comment by AtlasAutocode** [comment]
It looks like header styles were never expected to be implemented as toggle buttons.
To avoid the exception, you will need to provide iconData as well as tooltip.
The buttons will not give you the expected result since _getIsToggled also needs an update.
I have made changes that should address that issue and can issue a PR as part of other changes in progress.
Can I ask why you want headers as individual buttons? The toolbar is already very long.

**Comment by tbusot** [comment]
Thanks @AtlasAutocode - I completely missed the `QuillToolbarSelectHeaderStyleButtons` element.

I'm deciding between the QuillToolbar.simple and QuillToolbar() with `showHeaderStyle` and `QuillToolbarSelectHeaderStyleButtons` respectively. 

You're right, between those two options, there is no need to use the headers as toggleable.

**Comment by AtlasAutocode** [comment]
As a new contributor I am finding that the code is highly complex and not always easy to use (or fix problems). There are a tremendous number of options and not all options work or are obvious.
