### ISSUE TITLE
[Bug] value is not subtype Attribute<dynamic>

### ISSUE THREAD

**Issue by CatHood0** [singerdmx/flutter-quill#1887]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

9.3.19

### Steps to reproduce

It's simple:

1) add some random text
2) add new line
3) put align attribute (any) and write more random text
4) append a new line, and, when you try to write insertion error will be appears

### Expected results

The insertions works as should

### Actual results

Cannot insert align block attributes to new lines (i only test with this one)

### Code sample

<details><summary>Code sample</summary>

I'm using the original code from the package. But this is my editor:

```dart

//toolbar
class CustomQuillToolbar extends StatelessWidget {
  final QuillController controller;
  final String defaultFontFamily;
  final double toolbarSize;
  const CustomQuillToolbar({
    super.key,
    required this.controller,
    this.defaultFontFamily = Constant.DEFAULT_FONT_FAMILY,
    this.toolbarSize = 40,
  });

  @override
  Widget build(BuildContext context) {
    final QuillSimpleToolbarConfigurations configurations = toolbarConfigurations();
    List<Widget> childrenBuilder(BuildContext context) {
      final QuillSimpleToolbarConfigurations toolbarConfigurations = context.requireQuillSimpleToolbarConfigurations;
      final List<EmbedButtonBuilder>? theEmbedButtons = configurations.embedButtons;
      final double? globalIconSize = toolbarConfigurations.buttonOptions.base.iconSize;

      return <Widget>[
        QuillToolbarFontFamilyButton(
          options: toolbarConfigurations.buttonOptions.fontFamily.copyWith(initialValue: defaultFontFamily),
          controller: controller,
        ),
        QuillToolbarFontSizeButton(
          options: toolbarConfigurations.buttonOptions.fontSize.copyWith(
            initialValue: 'Normal',
            rawItemsMap: Constant.fontSizes,
          ),
          controller: controller,
        ),
        QuillLineHeightButton(
          options: const QuillLineHeightButtonOptions(defaultDisplayText: "1.0"),
          controller: controller,
        ),
        QuillToolbarToggleStyleButton(
          attribute: Attribute.bold,
          options: toolbarConfigurations.buttonOptions.bold,
          controller: controller,
        ),
        QuillToolbarToggleStyleButton(
          attribute: Attribute.italic,
          options: toolbarConfigurations.buttonOptions.italic,
          controller: controller,
        ),
        QuillToolbarToggleStyleButton(
          attribute: Attribute.underline,
          options: toolbarConfigurations.buttonOptions.underLine,
          controller: controller,
        ),
        if (theEmbedButtons != null)
          for (final EmbedButtonBuilder builder in theEmbedButtons)
            builder(controller, globalIconSize ?? kDefaultIconSize, context.quillToolbarBaseButtonOptions?.iconTheme,
                configurations.dialogTheme),
        QuillToolbarSelectAlignmentButtons(
          controller: controller,
          options: toolbarConfigurations.buttonOptions.selectAlignmentButtons.copyWith(
            showLeftAlignment: configurations.showLeftAlignment,
            showCenterAlignment: configurations.showCenterAlignment,
            showRightAlignment: configurations.showRightAlignment,
            showJustifyAlignment: configurations.showJustifyAlignment,
          ),
        ),
        QuillToolbarSelectHeaderStyleButtons(
          controller: controller,
          options: toolbarConfigurations.buttonOptions.selectHeaderStyleButtons,
        ),
        QuillToolbarToggleStyleButton(
          attribute: Attribute.ol,
          options: toolbarConfigurations.buttonOptions.listNumbers,
          controller: controller,
        ),
        QuillToolbarToggleStyleButton(
          attribute: Attribute.ul,
          options: toolbarConfigurations.buttonOptions.listBullets,
          controller: controller,
        ),
        QuillToolbarToggleCheckListButton(
          options: toolbarConfigurations.buttonOptions.toggleCheckList,
          controller: controller,
        ),
        QuillToolbarIndentButton(
          controller: controller,
          isIncrease: true,
          options: toolbarConfigurations.buttonOptions.indentIncrease,
        ),
        QuillToolbarIndentButton(
          controller: controller,
          isIncrease: false,
          options: toolbarConfigurations.buttonOptions.indentDecrease,
        ),
        toolbarConfigurations.linkStyleType.isOriginal
            ? QuillToolbarLinkStyleButton(
                controller: controller,
                options: toolbarConfigurations.buttonOptions.linkStyle,
              )
            : QuillToolbarLinkStyleButton2(
                controller: controller,
                options: toolbarConfigurations.buttonOptions.linkStyle2,
              ),
        QuillToolbarSearchButton(
          controller: controller,
          options: toolbarConfigurations.buttonOptions.search,
        ),
        QuillToolbarColorButton(
          controller: controller,
          isBackground: false,
          options: toolbarConfigurations.buttonOptions.color,
        ),
        QuillToolbarColorButton(
          options: toolbarConfigurations.buttonOptions.backgroundColor,
          controller: controller,
          isBackground: true,
        ),
        QuillToolbarClearFormatButton(
          controller: controller,
          options: toolbarConfigurations.buttonOptions.clearFormat,
        ),
      ];
    }

    return QuillSimpleToolbarProvider(
      toolbarConfigurations: configurations,
      child: QuillToolbar(
        configurations: QuillToolbarConfigurations(buttonOptions: configurations.buttonOptions),
        child: Builder(
          builder: (BuildContext context) {
            if (configurations.multiRowsDisplay) {
              return Wrap(
                direction: configurations.axis,
                alignment: configurations.toolbarIconAlignment,
                crossAxisAlignment: configurations.toolbarIconCrossAlignment,
                runSpacing: configurations.toolbarRunSpacing,
                spacing: configurations.toolbarSectionSpacing,
                children: childrenBuilder(context),
              );
            }
            return Container(
              decoration: configurations.decoration ??
                  BoxDecoration(
                    color: configurations.color ?? Theme.of(context).canvasColor,
                  ),
              constraints: BoxConstraints.tightFor(
                height: configurations.axis == Axis.horizontal ? configurations.toolbarSize : null,
                width: configurations.axis == Axis.vertical ? configurations.toolbarSize : null,
              ),
              child: QuillToolbarArrowIndicatedButtonList(
                axis: configurations.axis,
                buttons: childrenBuilder(context),
              ),
            );
          },
        ),
      ),
    );
  }

  QuillSimpleToolbarConfigurations toolbarConfigurations() {
    return QuillSimpleToolbarConfigurations(
      controller: controller,
      axis: Axis.horizontal,
      headerStyleType: HeaderStyleType.buttons,
      embedButtons: FlutterQuillEmbeds.toolbarButtons(videoButtonOptions: null),
      toolbarSize: toolbarSize,
      fontFamilyValues: Constant.fontFamilies,
      multiRowsDisplay: false,
      buttonOptions: const QuillSimpleToolbarButtonOptions(
        fontFamily: QuillToolbarFontFamilyButtonOptions(
          renderFontFamilies: true,
        ),
        selectAlignmentButtons: QuillToolbarSelectAlignmentButtonOptions(
          showCenterAlignment: true,
          showJustifyAlignment: true,
          showLeftAlignment: true,
          showRightAlignment: true,
          iconsData: QuillSelectAlignmentValues<IconData>(
            leftAlignment: Icons.format_align_left_outlined,
            centerAlignment: Icons.format_align_center_outlined,
            rightAlignment: Icons.format_align_right_outlined,
            justifyAlignment: Icons.format_align_justify_outlined,
          ),
        ),
      ),
      sharedConfigurations: const QuillSharedConfigurations(
        locale: Locale('en'),
      ),
    );
  }
}

//editor
class CustomQuillEditor extends HookWidget {
  final void Function(Document document) onChange;
  final QuillController controller;
  final FocusNode node;
  final ScrollController scrollController;
  final String? defaultFontFamily;
  const CustomQuillEditor({
    super.key,
    required this.onChange,
    required this.controller,
    required this.node,
    required this.scrollController,
    this.defaultFontFamily = Constant.DEFAULT_FONT_FAMILY,
  });

  @override
  Widget build(BuildContext context) {
    useEffect(() {
      controller.addListener(() => onChange(controller.document));
      return () => controller.removeListener(() => onChange(controller.document));
    }, <Object?>[controller.document]);
    return QuillEditor.basic(
      focusNode: node,
      scrollController: scrollController,
      configurations: QuillEditorConfigurations(
        embedBuilders: FlutterQuillEmbeds.editorBuilders(),

        controller: controller,
        textCapitalization: TextCapitalization.sentences,
        detectWordBoundary: true,
        placeholder: 'Write something',
        magnifierConfiguration: TextMagnifier.adaptiveMagnifierConfiguration,
        padding: EdgeInsets.only(bottom: 20),
        autoFocus: false,
        enableSelectionToolbar: true,
        enableInteractiveSelection: true,
        textSelectionControls: Platform.isAndroid ? MaterialTextSelectionControls() : DesktopTextSelectionControls(),
        customStyleBuilder: (Attribute<dynamic> attribute) {
          if (attribute.key.equals('line-height')) {
            return TextStyle(
              height: double.parse(attribute.value),
            );
          }
          if (attribute.key.equals('bold')) {
            return TextStyle(
              fontWeight: attribute.value ? FontWeight.bold : null,
            );
          }
          if (attribute.key.equals('italic')) {
            return TextStyle(
              fontStyle: attribute.value ? FontStyle.italic : null,
            );
          }
          if (attribute.key.equals('font')) {
            return TextStyle(
              fontFamily: attribute.value,
            );
          }
          if (attribute.key.equals('size')) {
            return TextStyle(
              fontSize: attribute.value.toString().resolveSize(),
            );
          }
          if (attribute.key.equals('header')) {
            return TextStyle(
              fontSize: '${attribute.value}'.resolveHeaderLevel(),
              color: Colors.black,
            );
          }
          //default | paragraph style
          return TextStyle(fontFamily: defaultFontFamily, height: 1.0);
        },
        customStyles: DefaultStyles(
          h1: const DefaultTextBlockStyle(TextStyle(), VerticalSpacing(10, 1), VerticalSpacing(5, 0), BoxDecoration()),
          h2: const DefaultTextBlockStyle(TextStyle(), VerticalSpacing(7, 1), VerticalSpacing(5, 0), BoxDecoration()),
          h3: const DefaultTextBlockStyle(TextStyle(), VerticalSpacing(4, 1), VerticalSpacing(5, 0), BoxDecoration()),
          indent: DefaultTextBlockStyle(
            TextStyle(color: Theme.of(context).textTheme.displayMedium!.color, fontSize: 16, fontFamily: defaultFontFamily, height: 1.15),
            const VerticalSpacing(0, 1),
            const VerticalSpacing(0, 0),
            const BoxDecoration(),
          ),
          lists: DefaultListBlockStyle(
            TextStyle(color: Theme.of(context).textTheme.displayMedium!.color, fontSize: 16, fontFamily: defaultFontFamily, height: 1.15),
            const VerticalSpacing(5, 0),
            const VerticalSpacing(0, 0),
            null,
            null,
          ),
          leading: DefaultTextBlockStyle(
            TextStyle(fontFamily: defaultFontFamily, fontSize: 16, height: 1.15, decoration: TextDecoration.none),
            const VerticalSpacing(0, 0),
            const VerticalSpacing(0, 0),
            null,
          ),
          code: DefaultTextBlockStyle(
              const TextStyle(fontSize: 11, fontFamily: 'monospace', color: Color.fromARGB(255, 255, 184, 78)),
              const VerticalSpacing(5, 5),
              const VerticalSpacing(5, 5),
              BoxDecoration(borderRadius: BorderRadius.circular(2), color: const Color.fromARGB(255, 234, 234, 234))),
          quote: DefaultTextBlockStyle(
            TextStyle(fontSize: 15, height: 1.15, fontFamily: defaultFontFamily, color: Colors.grey),
            const VerticalSpacing(0, 1),
            const VerticalSpacing(0, 0),
            const BoxDecoration(
              border: BorderDirectional(start: BorderSide(width: 5, color: Color.fromARGB(202, 255, 255, 255))),
              borderRadius: BorderRadius.only(topRight: Radius.circular(15), bottomRight: Radius.circular(15)),
              color: Color.fromARGB(15, 255, 255, 255),
            ),
          ),
          align: DefaultTextBlockStyle(
            TextStyle(color: Theme.of(context).textTheme.displayMedium!.color, height: 1.15, fontSize: 16, fontFamily: defaultFontFamily),
            const VerticalSpacing(0, 1),
            const VerticalSpacing(0, 0),
            const BoxDecoration(),
          ),
          paragraph: DefaultTextBlockStyle(
            TextStyle(color: Theme.of(context).textTheme.displayMedium!.color, height: 1.15, fontSize: 16, fontFamily: defaultFontFamily),
            const VerticalSpacing(0, 1),
            const VerticalSpacing(0, 0),
            const BoxDecoration(),
          ),
          link: const TextStyle(color: Color.fromARGB(255, 115, 192, 255)),
        ),
        elementOptions: const QuillEditorElementOptions(codeBlock: QuillEditorCodeBlockElementOptions(enableLineNumbers: true)),
        sharedConfigurations: const QuillSharedConfigurations(
          locale: Locale('en'),
        ),
      ),
    );
  }
}
```
</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

https://github.com/singerdmx/flutter-quill/assets/114286961/ae14014d-f9d3-40e0-810f-e71aad3dc224

</details>

### Logs

<details><summary>Logs</summary>

```console
The following _TypeError was thrown during method call TextInputClient.updateEditingState:
type 'String' is not a subtype of type 'Attribute<dynamic>' in type cast

When the exception was thrown, this was the stack:
#0      PreserveInlineStylesRule.applyRule (package:flutter_quill/src/models/rules/insert.dart:569:23)
insert.dart:569
#1      Rule.apply (package:flutter_quill/src/models/rules/rule.dart:24:12)
rule.dart:24
#2      Rules.apply (package:flutter_quill/src/models/rules/rule.dart:94:29)
rule.dart:94
#3      Document.insert (package:flutter_quill/src/models/documents/document.dart:85:26)
document.dart:85
#4      Document.replace (package:flutter_quill/src/models/documents/document.dart:143:17)
document.dart:143
#5      QuillController.replaceText (package:flutter_quill/src/widgets/quill/quill_controller.dart:260:24)
quill_controller.dart:260
#6      RawEditorStateTextInputClientMixin.updateEditingValue (package:flutter_quill/src/widgets/raw_editor/raw_editor_state_text_input_client_mixin.dart:202:40)
raw_editor_state_text_input_client_mixin.dart:202
#7      TextInput._updateEditingValue (package:flutter/src/services/text_input.dart:2061:43)
text_input.dart:2061
#8      TextInput._handleTextInputInvocation (package:flutter/src/services/text_input.dart:1894:29)
text_input.dart:1894
#9      TextInput._loudlyHandleTextInputInvocation (package:flutter/src/services/text_input.dart:1794:20)
text_input.dart:1794
#10     MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:571:55)
platform_channel.dart:571
#11     MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:564:34)
platform_channel.dart:564
#12     _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:581:35)
binding.dart:581
#13     _invoke2 (dart:ui/hooks.dart:344:13)
hooks.dart:344
#14     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:45:5)
channel_buffers.dart:45
#15     _Channel.push (dart:ui/channel_buffers.dart:135:31)
channel_buffers.dart:135
#16     ChannelBuffers.push (dart:ui/channel_buffers.dart:343:17)
channel_buffers.dart:343
#17     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:750:22)
platform_dispatcher.dart:750
#18     _dispatchPlatformMessage (dart:ui/hooks.dart:257:31)
hooks.dart:257

call: MethodCall(TextInputClient.updateEditingState, [1, {selectionBase: 25, selectionExtent: 25, composingBase: 24, text: Jcrjcryrcurv

Cjtivtitv
K
, composingExtent: 25}])

════════ Exception caught by services library ══════════════════════════════════
type 'String' is not a subtype of type 'Attribute<dynamic>' in type cast
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by services library ══════════════════════════════════
RangeError (end): Invalid value: Not in inclusive range 0..25: 26
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by services library ══════════════════════════════════
RangeError (end): Invalid value: Not in inclusive range 0..25: 27
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by services library ══════════════════════════════════
RangeError (end): Invalid value: Not in inclusive range 0..25: 28
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by services library ══════════════════════════════════
RangeError (end): Invalid value: Not in inclusive range 0..25: 29
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by services library ══════════════════════════════════
RangeError (end): Invalid value: Not in inclusive range 0..25: 30
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by services library ══════════════════════════════════
RangeError (end): Invalid value: Not in inclusive range 0..25: 31
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by services library ══════════════════════════════════
RangeError (end): Invalid value: Not in inclusive range 0..25: 32
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by services library ══════════════════════════════════
RangeError (end): Invalid value: Not in inclusive range 0..25: 33
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by services library ══════════════════════════════════
RangeError (end): Invalid value: Not in inclusive range 0..25: 34
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by services library ══════════════════════════════════
RangeError (end): Invalid value: Not in inclusive range 0..25: 35
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by services library ══════════════════════════════════
RangeError (end): Invalid value: Not in inclusive range 0..25: 36
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by services library ══════════════════════════════════
RangeError (end): Invalid value: Not in inclusive range 0..25: 37
════════ Exception caught by services library ══════════════════════════════════
RangeError (end): Invalid value: Not in inclusive range 0..77: 80
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by services library ══════════════════════════════════
RangeError (end): Invalid value: Not in inclusive range 0..77: 81
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by scheduler library ═════════════════════════════════
The provided text position is not in the current node
'package:flutter_quill/src/widgets/quill/text_block.dart':
Failed assertion: line 694 pos 12: 'container.containsOffset(position.offset)'
════════════════════════════════════════════════════════════════════════════════
```
</details>

**Comment by CatHood0** [comment]
@AtlasAutocode you should take a look about this

**Comment by EgorK0rshun** [comment]
++

**Comment by AtlasAutocode** [comment]
Can you check this out before I issue a pull request?
Comment out your current dependency for flutter_quill and replace it with my fork:

YAML:
dependencies:
  flutter_quill:
    git:
      url: 'https://github.com/AtlasAutocode/flutter-quill'

**Comment by CatHood0** [comment]
I will check it

**Comment by AtlasAutocode** [comment]
Thanks for checking.
I have learned 2 important lessons:
1. It is not a good idea to define your own Attributes - there is a lot of hard-coded use of the built in attributes.
2. properties called 'attributes' may not actually be a list of Attributes! In one case, it was actually a Map of key-value pairs that did not include the AttributeScope that your code depended on.

**Comment by ellet0** [comment]
> Thanks for checking.
> I have learned 2 important lessons:
> 1. It is not a good idea to define your own Attributes - there is a lot of hard-coded use of the built in attributes.
> 2. properties called 'attributes' may not actually be a list of Attributes! In one case, it was actually a Map of key-value pairs that did not include the AttributeScope that your code depended on.

I would want to refactor it and use sealed class, but it could introduce breaking changes (can be prevented) or other issues. It needs more testing, though the whole features that use the attributes as we don't have many tests about it
