### ISSUE TITLE
[Mobile] Odd behavior after undoing 2 typed characters or more

### ISSUE THREAD

**Issue by jongkb** [singerdmx/flutter-quill#190]
On Android, when typing several characters in quick succession and then invoking undo, platform exception is thrown:

`
E/MethodChannel#flutter/textinput(22657): Failed to handle method call
E/MethodChannel#flutter/textinput(22657): java.lang.IndexOutOfBoundsException: invalid composing start: 4
E/MethodChannel#flutter/textinput(22657): 	at io.flutter.embedding.engine.systemchannels.TextInputChannel$TextEditState.<init>(TextInputChannel.java:719)
E/MethodChannel#flutter/textinput(22657): 	at io.flutter.embedding.engine.systemchannels.TextInputChannel$TextEditState.fromJson(TextInputChannel.java:680)
E/MethodChannel#flutter/textinput(22657): 	at io.flutter.embedding.engine.systemchannels.TextInputChannel$1.onMethodCall(TextInputChannel.java:91)
E/MethodChannel#flutter/textinput(22657): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/MethodChannel#flutter/textinput(22657): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#flutter/textinput(22657): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/MethodChannel#flutter/textinput(22657): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#flutter/textinput(22657): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/MethodChannel#flutter/textinput(22657): 	at android.os.Looper.loop(Looper.java:174)
E/MethodChannel#flutter/textinput(22657): 	at android.app.ActivityThread.main(ActivityThread.java:7403)
E/MethodChannel#flutter/textinput(22657): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter/textinput(22657): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/MethodChannel#flutter/textinput(22657): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
`

Functionally, the undo action works but the moment a new character is typed, the editor prepends the undone text.

Minimal reproduction steps:
1. Type two characters in quick succession e.g. `ab`
2. Tap Undo button on the editor toolbar
3. Type a new character e.g. `c`

Actual: `abc` 
Expected: `c` 

Thanks.

**Comment by jongkb** [comment]
Resolved after upgrading to latest Flutter stable.
