### ISSUE TITLE
BuildContext error on "Paste a photo using a link" in Custom Toolbar Implementation

### ISSUE THREAD

**Issue by vinz-mehra** [singerdmx/flutter-quill#2043]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

10.0.2

### Steps to reproduce

1. Use the quill with the extension package
2. Display the custom toolbar implementation
3. Tap on the image button on the toolbar
4. Tap on "Paste a photo using a link"

### Expected results

A dialog to add link should open 

### Actual results

An error occurs saying  'The showDialog function context parameter is a BuildContext that is no longer valid.'

### Code sample

<details><summary>Code sample</summary>

```dart
class QuillToolbarDefault extends ConsumerWidget {
  const QuillToolbarDefault({super.key, required this.controller});

  final QuillController controller;

  Future<void> onImageInsertWithCropping(String image,
      QuillController controller, BuildContext context, bool isScribble) async {
    final croppedFile = await ImageCropper().cropImage(
      sourcePath: image,
      maxWidth: 800,
      compressFormat:
          isScribble ? ImageCompressFormat.png : ImageCompressFormat.jpg,
      uiSettings: [
        AndroidUiSettings(
          toolbarTitle: 'Crop Image',
          toolbarColor: primary,
          backgroundColor: background,
          toolbarWidgetColor: cardBackground,
          activeControlsWidgetColor: primary,
          initAspectRatio: CropAspectRatioPreset.original,
          lockAspectRatio: false,
        ),
        IOSUiSettings(
          title: 'Crop Image',
        ),
        WebUiSettings(
          context: context,
        ),
      ],
    );
    final newImage = croppedFile?.path;
    if (newImage == null) {
      return;
    }
    if (isWeb()) {
      controller.insertImageBlock(imageSource: newImage);
      return;
    }
    final newSavedImage = await saveImage(io.File(newImage));
    controller.insertImageBlock(imageSource: newSavedImage);
    addNewLine(controller);
  }

  void addNewLine(
    QuillController controller,
  ) {
    final int position = controller.selection.baseOffset;
    controller.document.insert(position, '\n');
    controller.document.insert(position + 1, '\n');
    controller.updateSelection(
      TextSelection.collapsed(offset: position + 3),
      ChangeSource.local,
    );
  }

  Future<void> onImageInsert(String image, QuillController controller) async {
    if (isWeb() || isHttpBasedUrl(image)) {
      controller.insertImageBlock(imageSource: image);
      addNewLine(controller);
      return;
    }
    final newSavedImage = await saveImage(io.File(image));
    controller.insertImageBlock(imageSource: newSavedImage);
    addNewLine(controller);
  }

  /// For mobile platforms it will copies the picked file from temporary cache
  /// to applications directory
  ///
  /// for desktop platforms, it will do the same but from user files this time
  Future<String> saveImage(io.File file) async {
    final newPath = await getImagePathFromDocumentWithFileName(file);
    final copiedFile = await file.copy(newPath);
    return copiedFile.path;
  }

  saveScribble(BuildContext context, ByteData image) async {
    final tempPath = await getTemporaryDirectory();
    final fileExt = path.extension('.png');
    final newFileName = '${DateTime.now().toIso8601String()}$fileExt';
    final newPath = path.join(
      tempPath.path,
      newFileName,
    );
    File(newPath).writeAsBytesSync(image.buffer.asUint8List());
    // ignore: use_build_context_synchronously
    onImageInsertWithCropping(newPath, controller, context, true);
  }

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    return QuillToolbar(
      configurations: const QuillToolbarConfigurations(),
      child: SingleChildScrollView(
        scrollDirection: Axis.horizontal,
        child: Wrap(
          children: [
            QuillToolbarHistoryButton(
              isUndo: true,
              controller: controller,
            ),
            QuillToolbarHistoryButton(
              isUndo: false,
              controller: controller,
            ),
            QuillToolbarImageButton(
              controller: controller,
              options: QuillToolbarImageButtonOptions(
                imageButtonConfigurations: QuillToolbarImageConfigurations(
                  onImageInsertCallback: isAndroid(supportWeb: false) ||
                          isIOS(supportWeb: false) ||
                          isWeb()
                      ? (image, controller) => onImageInsertWithCropping(
                          image, controller, context, false)
                      : onImageInsert,
                ),
              ),
            ),
            QuillToolbarCustomButton(
              controller: controller,
              options: QuillToolbarCustomButtonOptions(
                  icon: Icon(Icons.draw),
                  onPressed: () {
                    Navigator.push(
                      context,
                      MaterialPageRoute(
                          builder: (ctx) => ScribbleEditor(
                                saveScribble: (image) {
                                  saveScribble(ctx, image);
                                },
                              )),
                    );
                  }),
            ),
            QuillToolbarToggleCheckListButton(
              controller: controller,
            ),
            QuillToolbarToggleStyleButton(
              options: const QuillToolbarToggleStyleButtonOptions(),
              controller: controller,
              attribute: Attribute.bold,
            ),
            QuillToolbarToggleStyleButton(
              options: const QuillToolbarToggleStyleButtonOptions(),
              controller: controller,
              attribute: Attribute.italic,
            ),
            QuillToolbarToggleStyleButton(
              controller: controller,
              attribute: Attribute.underline,
            ),
            QuillToolbarToggleStyleButton(
              controller: controller,
              attribute: Attribute.subscript,
            ),
            QuillToolbarToggleStyleButton(
              controller: controller,
              attribute: Attribute.superscript,
            ),
            QuillToolbarSelectHeaderStyleButtons(controller: controller),
            QuillToolbarColorButton(
              controller: controller,
              isBackground: false,
            ),
            QuillToolbarColorButton(
              controller: controller,
              isBackground: true,
            ),
            QuillToolbarToggleStyleButton(
              controller: controller,
              attribute: Attribute.ol,
            ),
            QuillToolbarToggleStyleButton(
              controller: controller,
              attribute: Attribute.ul,
            ),
            QuillToolbarIndentButton(
              controller: controller,
              isIncrease: true,
            ),
            QuillToolbarIndentButton(
              controller: controller,
              isIncrease: false,
            ),
            QuillToolbarClearFormatButton(
              controller: controller,
            ),
          ],
        ),
      ),
    );
  }
}

```

</details>

### Additional Context

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

<details><summary>Logs</summary>

```console
E/flutter ( 6265): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: This BuildContext is no longer valid.
E/flutter ( 6265): The showDialog function context parameter is a BuildContext that is no longer valid.
E/flutter ( 6265): This can commonly occur when the showDialog function is called after awaiting a Future. In this situation the BuildContext might refer to a widget that has already been disposed during the await. Consider using a parent context instead.
E/flutter ( 6265): #0      _debugIsActive (package:flutter/src/material/dialog.dart:1504:5)
E/flutter ( 6265): #1      showDialog (package:flutter/src/material/dialog.dart:1425:10)
E/flutter ( 6265): #2      QuillToolbarImageButton._typeLink (package:flutter_quill_extensions/embeds/image/toolbar/image_button.dart:159:25)
E/flutter ( 6265): #3      QuillToolbarImageButton._onPressedHandler (package:flutter_quill_extensions/embeds/image/toolbar/image_button.dart:141:39)
```

</details>

**Comment by vinz-mehra** [comment]
Any updates on this?

**Comment by vinz-mehra** [comment]
For anyone facing the same issue. It was because of this part of the code

` 
if(keyboardIsVisible)
Padding(
              padding: globalMediumPadding(left: 0.h, right: 0.h, bottom: 13.h),
              child: QuillToolbarDefault(
                controller: _textController,
              )),`

It disposed of the widget every time a dialog opened, causing it to lose its state. I fixed it by changing the code to the following

` Visibility(
          visible: keyboardVisible,
          maintainState: true,
          child: Padding(
              padding: globalMediumPadding(left: 0.h, right: 0.h, bottom: 13.h),
              child: QuillToolbarDefault(
                controller: _textController,
              )),
        ),`
