### ISSUE TITLE
RenderBox was not laid out exception thrown when autofocus set to true and editor built immediately

### ISSUE THREAD

**Issue by realth000** [singerdmx/flutter-quill#2045]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

10.0.2 (689b8fde7c6c1622f79d155d90821589135541e4)

### Steps to reproduce

1. Apply this patch on example source code:
```diff
diff --git a/example/lib/main.dart b/example/lib/main.dart
index 2a8ed52c..06787144 100644
--- a/example/lib/main.dart
+++ b/example/lib/main.dart
@@ -6,8 +6,10 @@ import 'package:flutter_localizations/flutter_localizations.dart'
         GlobalCupertinoLocalizations,
         GlobalMaterialLocalizations,
         GlobalWidgetsLocalizations;
-import 'package:flutter_quill/flutter_quill.dart' show Document;
-import 'package:flutter_quill/translations.dart' show FlutterQuillLocalizations;
+import 'package:flutter_quill/flutter_quill.dart'
+    show Document, QuillController, QuillEditor, QuillEditorConfigurations;
+import 'package:flutter_quill/translations.dart'
+    show FlutterQuillLocalizations, FlutterQuillLocalizationsWidget;
 import 'package:flutter_quill_extensions/flutter_quill_extensions.dart';
 import 'package:hydrated_bloc/hydrated_bloc.dart'
     show HydratedBloc, HydratedStorage;
@@ -39,6 +41,39 @@ class MyApp extends StatelessWidget {
 
   @override
   Widget build(BuildContext context) {
+    final delay = false;
+    return MaterialApp(
+      home: Scaffold(
+        appBar: AppBar(title: Text('test')),
+        body: Column(
+          children: [
+            Expanded(
+              child: delay
+                  ? FutureBuilder(
+                      future: Future.value(''),
+                      builder: (context, snapshot) {
+                        if (!snapshot.hasData) {
+                          return Center(child: CircularProgressIndicator());
+                        }
+                        return QuillEditor.basic(
+                          configurations: QuillEditorConfigurations(
+                            autoFocus: true,
+                            controller: QuillController.basic(),
+                          ),
+                        );
+                      },
+                    )
+                  : QuillEditor.basic(
+                      configurations: QuillEditorConfigurations(
+                        autoFocus: true,
+                        controller: QuillController.basic(),
+                      ),
+                    ),
+            ),
+          ],
+        ),
+      ),
+    );
     return MultiBlocProvider(
       providers: [
         BlocProvider(
```
2. Run the example. For me is `cd example && flutter run -d Windows`

### Expected results

No exception in the 2. step.

### Actual results

2. step throwed exception:
```console
══╡ EXCEPTION CAUGHT BY FOUNDATION LIBRARY
╞════════════════════════════════════════════════════════
The following assertion was thrown while dispatching notifications for FocusNode:
RenderBox was not laid out: RenderEditor#df537 NEEDS-LAYOUT NEEDS-PAINT
NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 2165 pos 12: 'hasSize'

When the exception was thrown, this was the stack:
#2      RenderBox.size (package:flutter/src/rendering/box.dart:2165:12)
#3      RawEditorStateTextInputClientMixin._updateSizeAndTransform
(package:flutter_quill/src/editor/raw_editor/raw_editor_state_text_input_client_mixi
n.dart:356:33)
#4      RawEditorStateTextInputClientMixin.openConnectionIfNeeded
(package:flutter_quill/src/editor/raw_editor/raw_editor_state_text_input_client_mixi
n.dart:77:7)
#5      RawEditorStateTextInputClientMixin.openOrCloseConnection
(package:flutter_quill/src/editor/raw_editor/raw_editor_state_text_input_client_mixi
n.dart:45:7)
#6      QuillRawEditorState._handleFocusChanged
(package:flutter_quill/src/editor/raw_editor/raw_editor_state.dart:1421:5)
#7      ChangeNotifier.notifyListeners
(package:flutter/src/foundation/change_notifier.dart:433:24)
#8      FocusNode._notify (package:flutter/src/widgets/focus_manager.dart:1090:5)
#9      FocusManager.applyFocusChangesIfNeeded
(package:flutter/src/widgets/focus_manager.dart:1850:12)
(elided 4 frames from class _AssertionError and dart:async)

The FocusNode sending notification was:
  FocusNode#9ea8d([PRIMARY FOCUS])
════════════════════════════════════════════════════════════════════════════════════
════════════════
```

**After change `delay` to `true` (wrap editor in a `FutureBuilder`) no exception here.**

### Code sample

See the patch in reproduce step.

### Additional Context

<details>
<summary>flutter doctor -v</summary>

```console
[✓] Flutter (Channel stable, 3.22.3, on Microsoft Windows [版本 10.0.19045.4651], locale zh-CN)
    • Flutter version 3.22.3 on channel stable at C:\Programming\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b0850beeb2 (4 days ago), 2024-07-16 21:43:41 -0700
    • Engine revision 235db911ba
    • Dart version 3.4.4
    • DevTools version 2.34.3

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at C:\Programming\Android
    • Platform android-35, build-tools 35.0.0
    • ANDROID_SDK_ROOT = C:\Programming\Android
    • Java binary at: C:\Programming\AndroidStudio2024\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0--11609105)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.7.1)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.7.34009.444
    • Windows 10 SDK version 10.0.20348.0

[✓] Android Studio (version 2024.1)
    • Android Studio at C:\Programming\AndroidStudio2024
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0--11609105)

[✓] IntelliJ IDEA Ultimate Edition (version 2024.1)
    • IntelliJ at C:\Users\***\AppData\Local\Programs\IntelliJ IDEA Ultimate
    • Flutter plugin version 80.0.2
    • Dart plugin version 241.18808

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [版本 10.0.19045.4651]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 126.0.6478.182
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 126.0.2592.113

[!] Network resources
    ✗ A network error occurred while checking "https://maven.google.com/": 信号灯超时时间已到

! Doctor found issues in 1 category.
```

</details>

<details><summary>Logs</summary>

```console
══╡ EXCEPTION CAUGHT BY FOUNDATION LIBRARY
╞════════════════════════════════════════════════════════
The following assertion was thrown while dispatching notifications for FocusNode:
RenderBox was not laid out: RenderEditor#df537 NEEDS-LAYOUT NEEDS-PAINT
NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 2165 pos 12: 'hasSize'

When the exception was thrown, this was the stack:
#2      RenderBox.size (package:flutter/src/rendering/box.dart:2165:12)
#3      RawEditorStateTextInputClientMixin._updateSizeAndTransform
(package:flutter_quill/src/editor/raw_editor/raw_editor_state_text_input_client_mixi
n.dart:356:33)
#4      RawEditorStateTextInputClientMixin.openConnectionIfNeeded
(package:flutter_quill/src/editor/raw_editor/raw_editor_state_text_input_client_mixi
n.dart:77:7)
#5      RawEditorStateTextInputClientMixin.openOrCloseConnection
(package:flutter_quill/src/editor/raw_editor/raw_editor_state_text_input_client_mixi
n.dart:45:7)
#6      QuillRawEditorState._handleFocusChanged
(package:flutter_quill/src/editor/raw_editor/raw_editor_state.dart:1421:5)
#7      ChangeNotifier.notifyListeners
(package:flutter/src/foundation/change_notifier.dart:433:24)
#8      FocusNode._notify (package:flutter/src/widgets/focus_manager.dart:1090:5)
#9      FocusManager.applyFocusChangesIfNeeded
(package:flutter/src/widgets/focus_manager.dart:1850:12)
(elided 4 frames from class _AssertionError and dart:async)

The FocusNode sending notification was:
  FocusNode#9ea8d([PRIMARY FOCUS])
════════════════════════════════════════════════════════════════════════════════════
════════════════
```

</details>

**Comment by CatHood0** [comment]
You need to add a SingleChildScrollView to your column parent. This happens because the editor is expanding outside the screen

**Comment by realth000** [comment]
> You need to add a `SingleChildScrollView` to your `Column` parent. This happens because the editor is expanding outside the screen

Maybe not the root cause.

Change home screen to editor screen and enable `autofocus` produce same exception:

```diff
diff --git a/example/lib/main.dart b/example/lib/main.dart
index 2a8ed52c..14d7f763 100644
--- a/example/lib/main.dart
+++ b/example/lib/main.dart
@@ -113,6 +113,11 @@ class MyApp extends StatelessWidget {
             },
             home: Builder(
               builder: (context) {
+                return QuillScreen(
+                  args: QuillScreenArgs(
+                    document: Document.fromJson(quillTextSample),
+                  ),
+                );
                 final screen = switch (state.defaultScreen) {
                   DefaultScreen.home => const HomeScreen(),
                   DefaultScreen.settings => const SettingsScreen(),
diff --git a/example/lib/screens/quill/quill_screen.dart b/example/lib/screens/quill/quill_screen.dart
index 220ca8a7..399cde05 100644
--- a/example/lib/screens/quill/quill_screen.dart
+++ b/example/lib/screens/quill/quill_screen.dart
@@ -102,6 +102,7 @@ class _QuillScreenState extends State<QuillScreen> {
               return Expanded(
                 child: MyQuillEditor(
                   configurations: QuillEditorConfigurations(
+                    autoFocus: true,
                     sharedConfigurations: _sharedConfigurations,
                     controller: _controller,
                   ),
```

Is this a proper reproduce step, or any other constraints in the example code?

**Comment by realth000** [comment]
> You need to add a `SingleChildScrollView` to your `Column` parent. This happens because the editor is expanding outside the screen

Could you take a look at the new example ? It only changes the default page.
