### ISSUE TITLE
[Android] Null check operator used on a null value in _showMagnifier(text_selection.dart:436)

### ISSUE THREAD

**Issue by stepushchik** [singerdmx/flutter-quill#2109]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

10.1.10

### Steps to reproduce

1. Select some text
2. Copy via context menu
3. Try to paste by long tap

### Expected results

Text has been pasted into the editor.

### Actual results

`Null check operator used on a null value in _showMagnifier(text_selection.dart:436)`

### Code sample

<details><summary>Code sample</summary>

```dart
text_selection.dart

_magnifierController.show(
  context: context,
  below: magnifierConfiguration.shouldDisplayHandlesInMagnifier
      ? null
      : _handles![0],
  builder: (_) => builtMagnifier,
);
```

</details>

### Additional Context

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

<details><summary>Logs</summary>

```console
Null check operator used on a null value:
                 #0      EditorTextSelectionOverlay._showMagnifier (package:flutter_quill/src/editor/widgets/text/text_selection.dart:436:21)
                 #1      EditorTextSelectionOverlay.showMagnifier (package:flutter_quill/src/editor/widgets/text/text_selection.dart:403:5)
                 #2      QuillRawEditorState.showMagnifier (package:flutter_quill/src/editor/raw_editor/raw_editor_state.dart:1837:24)
                 #3      _QuillEditorSelectionGestureDetectorBuilder._showMagnifierIfSupportedByPlatform (package:flutter_quill/src/editor/editor.dart:656:17)
                 #4      _QuillEditorSelectionGestureDetectorBuilder.onSingleLongTapStart (package:flutter_quill/src/editor/editor.dart:629:5)
                 #5      _EditorTextSelectionGestureDetectorState._handleLongPressStart (package:flutter_quill/src/editor/widgets/text/text_selection.dart:1042:36)
                 #6      LongPressGestureRecognizer._checkLongPressStart.<anonymous closure> (package:flutter/src/gestures/long_press.dart:703:75)
```

</details>

**Comment by stepushchik** [comment]
"Fixed" for now by
`magnifierConfiguration: TextMagnifierConfiguration.disabled` in `QuillEditorConfigurations`
