### ISSUE TITLE
[Mobile] Invalid composing start while trying to reset the content of the editor

### ISSUE THREAD

**Issue by dchrzanowski** [singerdmx/flutter-quill#213]
My issue is about [Mobile]

I have tried running `example` directory successfully before creating an issue here.

I am trying to programmatically wipe the content of the quill editor. 
So far either recreating the controller and calling setState or recreating the document and the controller end with a failure. Also replacing the whole text ends with a failure.

So I have tried this:

```dart
_controller.replaceText(
  0,
  _controller.document.length - 1,
  "\n",
  TextSelection.collapsed(offset: 0),
);
setState(() {});
```

And this:

```dart
var delta = Delta()..push(Operation.insert(' \n'));
var doc = Document.fromDelta(delta);
_controller = QuillController(
  document: doc,
  selection: TextSelection.collapsed(offset: 0),
);
setState(() {});
```

And finally this:

```dart
_controller = QuillController.basic();
setState(() {});
```

Surprisingly sometimes it "JUST WORKS" but most of the time it does not. This inconsistency is curious to say the least. 
Every option produces this error:

```
E/MethodChannel#flutter/textinput(10605): Failed to handle method call
E/MethodChannel#flutter/textinput(10605): java.lang.IndexOutOfBoundsException: invalid composing start: 0
E/MethodChannel#flutter/textinput(10605): 	at io.flutter.embedding.engine.systemchannels.TextInputChannel$TextEditState.<init>(TextInputChannel.java:719)
E/MethodChannel#flutter/textinput(10605): 	at io.flutter.embedding.engine.systemchannels.TextInputChannel$TextEditState.fromJson(TextInputChannel.java:680)
E/MethodChannel#flutter/textinput(10605): 	at io.flutter.embedding.engine.systemchannels.TextInputChannel$1.onMethodCall(TextInputChannel.java:91)
E/MethodChannel#flutter/textinput(10605): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/MethodChannel#flutter/textinput(10605): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#flutter/textinput(10605): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/MethodChannel#flutter/textinput(10605): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#flutter/textinput(10605): 	at android.os.MessageQueue.next(MessageQueue.java:335)
E/MethodChannel#flutter/textinput(10605): 	at android.os.Looper.loop(Looper.java:183)
E/MethodChannel#flutter/textinput(10605): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/MethodChannel#flutter/textinput(10605): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter/textinput(10605): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/MethodChannel#flutter/textinput(10605): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/flutter (10605): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: PlatformException(error, invalid composing start: 0, null, java.lang.IndexOutOfBoundsException: invalid composing start: 0
E/flutter (10605): 	at io.flutter.embedding.engine.systemchannels.TextInputChannel$TextEditState.<init>(TextInputChannel.java:719)
E/flutter (10605): 	at io.flutter.embedding.engine.systemchannels.TextInputChannel$TextEditState.fromJson(TextInputChannel.java:680)
E/flutter (10605): 	at io.flutter.embedding.engine.systemchannels.TextInputChannel$1.onMethodCall(TextInputChannel.java:91)
E/flutter (10605): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/flutter (10605): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/flutter (10605): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/flutter (10605): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (10605): 	at android.os.MessageQueue.next(MessageQueue.java:335)
E/flutter (10605): 	at android.os.Looper.loop(Looper.java:183)
E/flutter (10605): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/flutter (10605): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (10605): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/flutter (10605): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/flutter (10605): )
E/flutter (10605): #0      JSONMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:158:7)
E/flutter (10605): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158:18)
E/flutter (10605): <asynchronous suspension>
E/flutter (10605): 
```

Weirdly enough I have a method to append a mention at the end of the editable text and this works just fine!

```dart
  void _insertMention(UserDTO user) {
    var oldDelta = _controller.document.toDelta();
    var trim = 1;

    // trim one whitespace if its there
    if (_controller.document.toPlainText().endsWith(' \n')) {
      trim++;
    }
    // copy old bit without the trailing newline
    oldDelta = oldDelta.slice(0, _controller.document.length - trim);
    // insert the link
    oldDelta
      ..trim()
      ..push(Operation.insert(' @'))
      ..push(Operation.insert(
        user.name,
        {'link': 'mention://user/' + user.id},
      ))
      ..push(Operation.insert('\n'));

    // recreate the document
    var doc = Document.fromDelta(oldDelta);
    _controller = QuillController(
      document: doc,
      selection: TextSelection.collapsed(offset: doc.length - 1),
    );

    setState(() {});
  }

```

**Comment by dchrzanowski** [comment]
Quick workaround seems to be doing this:

```dart
_focusNode.unfocus();
_controller = QuillController.basic();
setState(() {});
```

But then the keyboard closes, don't exactly want that. But it will do for the time being.

Just in-case the editor is instantiated like so:

```dart
child: QuillEditor(
  maxHeight: 200,
  controller: _controller,
  scrollController: ScrollController(),
  scrollable: true,
  focusNode: _focusNode,
  autoFocus: false,
  readOnly: false,
  placeholder: 'New message...',
  expands: false,
  padding: EdgeInsets.only(left: 8),
  showCursor: true,
),
```
