### ISSUE TITLE
Bad state: No element

### ISSUE THREAD

**Issue by tschiekdev** [singerdmx/flutter-quill#2272]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

10.7.5

### Steps to reproduce

dont know

### Expected results

no exception

### Actual results

#0 _Array.first (dart:core-patch/array.dart:52)
#1 RenderEditableTextLine._getEndpointForSelection (package:flutter_quill/src/editor/widgets/text/text_line.dart:928)
#2 RenderEditableTextLine.getBaseEndpointForSelection (package:flutter_quill/src/editor/widgets/text/text_line.dart:909)
#3 RenderEditor.getEndpointsForSelection (package:flutter_quill/src/editor/editor.dart:901)
#4 RenderEditor.getOffsetToRevealCursor (package:flutter_quill/src/editor/editor.dart:1288)
#5 QuillRawEditorState._showCaretOnScreen.<anonymous closure> (package:flutter_quill/src/editor/raw_editor/raw_editor_state.dart:1169)
#6 SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1397)
#7 SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1331)
#8 SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1176)
#9 _rootRun (dart:async/zone.dart:1399)
#10 _CustomZone.run (dart:async/zone.dart:1301)
#11 _CustomZone.runGuarded (dart:async/zone.dart:1209)
#12 _invoke (dart:ui/hooks.dart:314)
#13 PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:419)
#14 _drawFrame (dart:ui/hooks.dart:283)

### Additional Context

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by CatHood0** [comment]
Can you tell us the steps you took to create this problem?

**Comment by tschiekdev** [comment]
> @tschiekdev Can you tell us the steps you took to create this problem? If you can provide a video, could be useful.

No, unfortunately not. The users use my app and the error handler catches the errors.

It would be desirable if the quill editor would not produce so many errors and would work more stable and reliable.

**Comment by EchoEllet** [comment]
> It would be desirable if the quill editor would not produce so many errors and would work more stable and reliable.

That's what we're working on, we will need more details to start providing the fix.

**Comment by CatHood0** [comment]
Which version are you using? I know 10.7.5, but if i check the line 928 of `text_line` i expected found a assertion, but i found just a method. Probably we need more detail to reproduce this error.
