### ISSUE TITLE
Null check operator used on a null value in History

### ISSUE THREAD

**Issue by tschiekdev** [singerdmx/flutter-quill#2278]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

10.7.5

### Steps to reproduce

History action

### Expected results

no error

### Actual results

```console
#0 QuillContainer.delete (package:flutter_quill\/src\/document\/nodes\/container.dart:169)
#1 Document.compose (package:flutter_quill\/src\/document\/document.dart:413)
#2 History._change (package:flutter_quill\/src\/document\/history.dart:107)
#3 History.undo (package:flutter_quill\/src\/document\/history.dart:113)
#4 Document.undo (package:flutter_quill\/src\/document\/document.dart:434)
#5 QuillController.undo (package:flutter_quill\/src\/controller\/quill_controller.dart:253)
#6 QuillToolbarHistoryButtonState._updateHistory (package:flutter_quill\/src\/toolbar\/buttons\/history_button.dart:108)
#7 QuillToolbarIconButton.build. (package:flutter_quill\/src\/toolbar\/buttons\/quill_icon_button.dart:31)
#8 _InkResponseState.handleTap (package:flutter\/src\/material\/ink_well.dart:1170)
#9 GestureRecognizer.invokeCallback (package:flutter\/src\/gestures\/recognizer.dart:351)
#10 TapGestureRecognizer.handleTapUp (package:flutter\/src\/gestures\/tap.dart:656)
#11 BaseTapGestureRecognizer._checkUp (package:flutter\/src\/gestures\/tap.dart:313)
#12 BaseTapGestureRecognizer.acceptGesture (package:flutter\/src\/gestures\/tap.dart:283)
#13 GestureArenaManager.sweep (package:flutter\/src\/gestures\/arena.dart:169)
#14 GestureBinding.handleEvent (package:flutter\/src\/gestures\/binding.dart:505)
#15 GestureBinding.dispatchEvent (package:flutter\/src\/gestures\/binding.dart:481)
#16 RendererBinding.dispatchEvent (package:flutter\/src\/rendering\/binding.dart:450)
#17 GestureBinding._handlePointerEventImmediately (package:flutter\/src\/gestures\/binding.dart:426)
#18 GestureBinding.handlePointerEvent (package:flutter\/src\/gestures\/binding.dart:389)
#19 GestureBinding._flushPointerEventQueue (package:flutter\/src\/gestures\/binding.dart:336)
#20 GestureBinding._handlePointerDataPacket (package:flutter\/src\/gestures\/binding.dart:305)
#21 _rootRunUnary (dart:async\/zone.dart:1415)
#22 _CustomZone.runUnary (dart:async\/zone.dart:1308)
#23 _CustomZone.runUnaryGuarded (dart:async\/zone.dart:1217)
#24 _invoke1 (dart:ui\/hooks.dart:330)
#25 PlatformDispatcher._dispatchPointerDataPacket (dart:ui\/platform_dispatcher.dart:442)
#26 _dispatchPointerDataPacket (dart:ui\/hooks.dart:262)\n
```

### Additional Context

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by AtlasAutocode** [comment]
Can you tell us the steps you took to create this problem.
In order to enable history, you must have entered something or done something?

**Comment by AtlasAutocode** [comment]
It is very hard to fix a problem when we do not know what was done to cause the error.
I have never encountered this error and there are no current reports of an error like this.

From the stack trace, it appears your user is performing an **undo** operation, and the document is **empty**.
This is an unexpected error that would be caught by an assert failure in debug mode when you were developing your app.

From what your app does, can you tell us what they might have done? 
Or at least, what platform your app is for? There can be critical differences between desktop, mobile and web.
Does your app replace the quill document or have any special operations that the user might have selected?
Does your user's copy of your app really use version 10.7.5 which is only a few days old? Perhaps their copy of your app was using an earlier version?

As a fellow developer, you understand that fixing a problem needs information on how to reproduce a problem.

**Comment by EchoEllet** [comment]
> fixing a problem needs information on how to reproduce a problem.

> It would be desirable if the quill editor would not produce so many errors and would work more stable and reliable.

I agree with both of you. One of the requirement to have a stable version of this project is to fix common issues, and we're trying to fix more than one issue, which is why we need more details, perhaps you can try to reproduce it or see if you can find more details.

**Comment by EchoEllet** [comment]
Closing the issue as we didn't receive a response.
