### ISSUE TITLE
Compatibility Issue with HarmonyOS has error

### ISSUE THREAD

**Issue by shanshen6** [singerdmx/flutter-quill#2389]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Use case

https://gitee.com/harmonycommando_flutter/flutter

flutter build hap
start hap build...
../../../.pub-cache/hosted/pub.flutter-io.cn/flutter_quill-10.8.5/lib/src/editor/widgets/delegate.dart:269:13:
Error: The type 'TargetPlatform' is not exhaustively matched by the switch cases since it doesn't match
'TargetPlatform.ohos'.
 - 'TargetPlatform' is from 'package:flutter/src/foundation/platform.dart'
 ('../../../ohos/flutter/packages/flutter/lib/src/foundation/platform.dart').
Try adding a default case or cases that match 'TargetPlatform.ohos'.
    switch (defaultTargetPlatform) {
            ^
../../../.pub-cache/hosted/pub.flutter-io.cn/flutter_quill-10.8.5/lib/src/editor/widgets/delegate.dart:479:13:
Error: The type 'TargetPlatform' is not exhaustively matched by the switch cases since it doesn't match
'TargetPlatform.ohos'.
 - 'TargetPlatform' is from 'package:flutter/src/foundation/platform.dart'
 ('../../../ohos/flutter/packages/flutter/lib/src/foundation/platform.dart').
Try adding a default case or cases that match 'TargetPlatform.ohos'.
    switch (defaultTargetPlatform) {
            ^
../../../.pub-cache/hosted/pub.flutter-io.cn/flutter_quill-10.8.5/lib/src/editor/widgets/delegate.dart:625:13:
Error: The type 'TargetPlatform' is not exhaustively matched by the switch cases since it doesn't match
'TargetPlatform.ohos'.
 - 'TargetPlatform' is from 'package:flutter/src/foundation/platform.dart'
 ('../../../ohos/flutter/packages/flutter/lib/src/foundation/platform.dart').
Try adding a default case or cases that match 'TargetPlatform.ohos'.
    switch (defaultTargetPlatform) {
            ^
../../../.pub-cache/hosted/pub.flutter-io.cn/flutter_quill-10.8.5/lib/src/editor/widgets/delegate.dart:679:15:
Error: The type 'TargetPlatform' is not exhaustively matched by the switch cases since it doesn't match
'TargetPlatform.ohos'.
 - 'TargetPlatform' is from 'package:flutter/src/foundation/platform.dart'
 ('../../../ohos/flutter/packages/flutter/lib/src/foundation/platform.dart').
Try adding a default case or cases that match 'TargetPlatform.ohos'.
      switch (defaultTargetPlatform) {
              ^
../../../.pub-cache/hosted/pub.flutter-io.cn/flutter_quill-10.8.5/lib/src/editor/widgets/delegate.dart:693:15:
Error: The type 'TargetPlatform' is not exhaustively matched by the switch cases since it doesn't match
'TargetPlatform.ohos'.
 - 'TargetPlatform' is from 'package:flutter/src/foundation/platform.dart'
 ('../../../ohos/flutter/packages/flutter/lib/src/foundation/platform.dart').
Try adding a default case or cases that match 'TargetPlatform.ohos'.
      switch (defaultTargetPlatform) {
              ^
../../../.pub-cache/hosted/pub.flutter-io.cn/flutter_quill-10.8.5/lib/src/editor/widgets/delegate.dart:803:17:
Error: The type 'TargetPlatform' is not exhaustively matched by the switch cases since it doesn't match
'TargetPlatform.ohos'.
 - 'TargetPlatform' is from 'package:flutter/src/foundation/platform.dart'
 ('../../../ohos/flutter/packages/flutter/lib/src/foundation/platform.dart').
Try adding a default case or cases that match 'TargetPlatform.ohos'.
        switch (defaultTargetPlatform) {
                ^
../../../.pub-cache/hosted/pub.flutter-io.cn/flutter_quill-10.8.5/lib/src/editor/widgets/delegate.dart:843:15:
Error: The type 'TargetPlatform' is not exhaustively matched by the switch cases since it doesn't match
'TargetPlatform.ohos'.
 - 'TargetPlatform' is from 'package:flutter/src/foundation/platform.dart'
 ('../../../ohos/flutter/packages/flutter/lib/src/foundation/platform.dart').
Try adding a default case or cases that match 'TargetPlatform.ohos'.
      switch (defaultTargetPlatform) {
              ^
../../../.pub-cache/hosted/pub.flutter-io.cn/flutter_quill-10.8.5/lib/src/editor/widgets/text/text_selection.da
rt:911:13: Error: The type 'TargetPlatform' is not exhaustively matched by the switch cases since it doesn't
match 'TargetPlatform.ohos'.
 - 'TargetPlatform' is from 'package:flutter/src/foundation/platform.dart'
 ('../../../ohos/flutter/packages/flutter/lib/src/foundation/platform.dart').
Try adding a default case or cases that match 'TargetPlatform.ohos'.
    switch (defaultTargetPlatform) {
            ^
../../../.pub-cache/hosted/pub.flutter-io.cn/flutter_quill-10.8.5/lib/src/editor/widgets/text/text_selection.da
rt:1068:15: Error: The type 'TargetPlatform' is not exhaustively matched by the switch cases since it doesn't
match 'TargetPlatform.ohos'.
 - 'TargetPlatform' is from 'package:flutter/src/foundation/platform.dart'
 ('../../../ohos/flutter/packages/flutter/lib/src/foundation/platform.dart').
Try adding a default case or cases that match 'TargetPlatform.ohos'.
      switch (defaultTargetPlatform) {
              ^
Target kernel_snapshot failed: Exception
#0      KernelSnapshot.build (package:flutter_tools/src/build_system/targets/common.dart:279:7)
<asynchronous suspension>
#1      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:875:9)
<asynchronous suspension>
#2      Future.wait.<anonymous closure> (dart:async/future.dart:524:21)
<asynchronous suspension>
#3      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:813:32)
<asynchronous suspension>
#4      Future.wait.<anonymous closure> (dart:async/future.dart:524:21)
<asynchronous suspension>
#5      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:813:32)
<asynchronous suspension>
#6      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:642:16)
<asynchronous suspension>
#7      flutterAssemble (package:flutter_tools/src/ohos/hvigor.dart:306:32)
<asynchronous suspension>
#8      OhosHvigorBuilder.flutterBuildPre (package:flutter_tools/src/ohos/hvigor.dart:543:27)
<asynchronous suspension>
#9      OhosHvigorBuilder.buildApplicationPipeLine (package:flutter_tools/src/ohos/hvigor.dart:681:5)
<asynchronous suspension>
#10     OhosHvigorBuilder.buildHap (package:flutter_tools/src/ohos/hvigor.dart:479:5)
<asynchronous suspension>
#11     BuildHapCommand.runCommand (package:flutter_tools/src/commands/build_hap.dart:80:5)
<asynchronous suspension>
#12     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1394:27)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#14     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#15     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:372:9)
<asynchronous suspension>
#16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#17     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:308:5)
<asynchronous suspension>
#18     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)
<asynchronous suspension>
#19     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#20     main (package:flutter_tools/executable.dart:93:3)
<asynchronous suspension>

Error: Failed to compile application for the Ohos.
Running Hvigor task assembleHap...       

### Proposal

Dear Flutter Quill Team,

We are currently using Flutter Quill as a cross-platform editor in our project. However, we have encountered several issues when trying to adapt it for HarmonyOS. Specifically, when running the flutter build hap command, we are faced with numerous errors that prevent us from successfully building the application for HarmonyOS.

Steps to Reproduce:

Set up a Flutter project with Flutter Quill as a dependency.
Attempt to build the project for HarmonyOS using the flutter build hap command.
Observe the errors that occur during the build process.

Expected Behavior:

The project should build successfully for HarmonyOS without any errors.

Actual Behavior:

The build process fails with multiple errors, indicating compatibility issues with HarmonyOS.

Error Logs:

(Include any relevant error logs or screenshots here)

Environment:

Flutter version: (include your Flutter version here)
Dart version: (include your Dart version here)
Flutter Quill version: (include the version of Flutter Quill you are using)
HarmonyOS version: (include the version of HarmonyOS you are targeting)

Additional Context:

We believe that resolving these compatibility issues would greatly benefit the Flutter community, as it would enable more developers to use Flutter Quill in their HarmonyOS projects. We would appreciate any assistance or guidance you can provide to help us overcome these challenges.

Thank you for your attention to this matter. We look forward to your response.

Best regards,

**Comment by shanshen6** [comment]
we need  use it  in  https://gitee.com/harmonycommando_flutter/flutter  
what show we do

**Comment by shanshen6** [comment]
<img width="667" alt="image" src="https://github.com/user-attachments/assets/3391bf2f-6206-4676-b981-f945c4ff4935">
Dear Flutter Quill Team,

We are currently using Flutter Quill as a cross-platform editor in our project. However, we have encountered several issues when trying to adapt it for HarmonyOS. Specifically, the [delegate.dart](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html) file does not seem to be fully compatible with HarmonyOS. When running the flutter build hap command, we encounter numerous errors related to the lack of support for TargetPlatform.ohos.

Details:

File: [delegate.dart](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html)
Issue: The file does not handle TargetPlatform.ohos in various switch statements, leading to build errors when targeting HarmonyOS.
Example:
In the onTapDown method, the TargetPlatform.ohos case is missing.
In the onDragSelectionUpdate method, the TargetPlatform.ohos case is not properly handled.
Steps to Reproduce:

Set up a Flutter project with Flutter Quill as a dependency.
Attempt to build the project for HarmonyOS using the flutter build hap command.
Observe the errors that occur during the build process.
Expected Behavior:

The project should build successfully for HarmonyOS without any errors.

Actual Behavior:

The build process fails with multiple errors, indicating compatibility issues with HarmonyOS.

Error Logs:

(Include any relevant error logs or screenshots here)

Environment:

Flutter version: (include your Flutter version here)
Dart version: (include your Dart version here)
Flutter Quill version: (include the version of Flutter Quill you are using)
HarmonyOS version: (include the version of HarmonyOS you are targeting)

Additional Context:

We believe that resolving these compatibility issues would greatly benefit the Flutter community, as it would enable more developers to use Flutter Quill in their HarmonyOS projects. We would appreciate any assistance or guidance you can provide to help us overcome these challenges.

Thank you for your attention to this matter. We look forward to your response.

Best regards,

**Comment by mny459** [comment]
Same issue.

**Comment by EchoEllet** [comment]
A workaround:

```dart
switch (defaultTargetPlatform) {
  case TargetPlatform.android:
  case TargetPlatform.ohos:
  // Assuming HarmonyOS has the same behavior as Android...
  break;
}
```

The project uses plugins and dependencies that don't support HarmonyOS yet, so it will probably have broken behavior and buggy.

**Comment by wangjinshan** [comment]
Subject: Issues with HarmonyOS Case Implementation in Flutter Quill

Hi ,

I hope this email finds you well.

I wanted to bring to your attention some issues we've encountered with the recent implementation of the HarmonyOS (ohos) case in the Flutter Quill package. Specifically, we noticed that treating the HarmonyOS case the same as the Android case has led to several problems:

Paste Functionality: The paste functionality is not working as expected.
Magnifier Feature: The magnifier feature cannot be disabled.
Image Insertion: We are unable to insert images.
These issues are critical for our application, and it appears that a short-term fix might not be feasible.

Could you please look into these problems and provide guidance on how we can resolve them?

Is there any developer currently using this SDK on HarmonyOS? There isn't a good editor available for HarmonyOS right now, and this SDK is definitely going to be the top choice for a rich text editor on HarmonyOS in the future.

Thank you for your attention to this matter.

Best regards

**Comment by EchoEllet** [comment]
> Image Insertion: We are unable to insert images.
These issues are critical for our application, and it appears that a short-term fix might not be feasible.
> Could you please look into these problems and provide guidance on how we can resolve them?

As [I mentioned previously](https://github.com/singerdmx/flutter-quill/issues/2392#issuecomment-2493250392), most of those functionalities are either platform behavior or require platform native code, the project uses dependencies and plugins that don't support **HarmonyOS**, and supporting a new platform isn't something we plan on.

I strongly prefer fewer features that are done well and not half-baked solutions.
