### ISSUE TITLE
[Mobile] Exception thrown ("targetChild should not be null") when deleting highlighted text

### ISSUE THREAD

**Issue by adamkoch** [singerdmx/flutter-quill#348]
Environment:
 - Flutter 2.2.3 • channel stable
 - flutter_quill: ^1.9.1

Repro steps:
 - Open flutter-quill editor in an app on iOS simulator (i have yet to check on a real iPhone as I don't have one available right now)
 - type out some text, then select all the text
 - choose "cut" or hit delete to remove the highlighted text
 - see `targetChild should not be null` exception as per below

Appreciate the awesome library and the work you do on it, thank you!

```
The following message was thrown building _TextSelectionHandleOverlay(dirty, dependencies: [_InheritedCupertinoTheme, _EffectiveTickerMode], state: _TextSelectionHandleOverlayState#421eb(ticker inactive)):
targetChild should not be null

The relevant error-causing widget was: 
  MaterialApp file:///Users/adam/src/app/lib/screens/root.dart:192:12
When the exception was thrown, this was the stack: 
#0      RenderEditableContainerBox.childAtPosition (package:flutter_quill/src/widgets/editor.dart:1140:7)
#1      RenderEditor.preferredLineHeight (package:flutter_quill/src/widgets/editor.dart:989:19)
#2      _TextSelectionHandleOverlayState.build (package:flutter_quill/src/widgets/text_selection.dart:447:45)
#3      StatefulElement.build (package:flutter/src/widgets/framework.dart:4691:27)
#4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4574:15)
...
====================================================================================================
```

**Comment by singerdmx** [comment]
@li3317 could you take a look please?

**Comment by GoodM4ven** [comment]
```
════════ Exception caught by widgets library ═══════════════════════════════════
The following message was thrown building _TextSelectionHandleOverlay(dirty, dependencies: [_InheritedTheme, _EffectiveTickerMode, _LocalizationsScope-[GlobalKey#2e061]], state: _TextSelectionHandleOverlayState#e2c98(ticker inactive)):
targetChild should not be null

The relevant error-causing widget was
GetMaterialApp
lib\main.dart:31
When the exception was thrown, this was the stack
#0      RenderEditableContainerBox.childAtPosition
package:flutter_quill/…/widgets/editor.dart:1145
#1      RenderEditor.preferredLineHeight
package:flutter_quill/…/widgets/editor.dart:994
#2      _TextSelectionHandleOverlayState.build
package:flutter_quill/…/widgets/text_selection.dart:451
#3      StatefulElement.build
package:flutter/…/widgets/framework.dart:4782
#4      ComponentElement.performRebuild
package:flutter/…/widgets/framework.dart:4665
#21     ComponentElement.performRebuild
package:flutter/…/widgets/framework.dart:4690
#22     StatefulElement.performRebuild
package:flutter/…/widgets/framework.dart:4840
#23     Element.rebuild
package:flutter/…/widgets/framework.dart:4355
#24     BuildOwner.buildScope
package:flutter/…/widgets/framework.dart:2620
#25     WidgetsBinding.drawFrame
package:flutter/…/widgets/binding.dart:882
#26     RendererBinding._handlePersistentFrameCallback
package:flutter/…/rendering/binding.dart:319
#27     SchedulerBinding._invokeFrameCallback
package:flutter/…/scheduler/binding.dart:1143
#28     SchedulerBinding.handleDrawFrame
package:flutter/…/scheduler/binding.dart:1080
#29     SchedulerBinding._handleDrawFrame
package:flutter/…/scheduler/binding.dart:996
#33     _invoke (dart:ui/hooks.dart:166:10)
#34     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:270:5)
#35     _drawFrame (dart:ui/hooks.dart:129:31)
(elided 3 frames from dart:async)
```

**Comment by myroid** [comment]
Thanks, this library is very useful to me.

This error will occur when the content of the Document is empty. E.g:
```dart
setState(() {
    _controller = QuillController(
      document: Document(), // this is the reason.
      selection: const TextSelection.collapsed(offset: 0),
    );
});
```

This is also the reason why Demo is so much.
https://github.com/singerdmx/flutter-quill/blob/3a0add9a4c3ab09ebfadd4502d210a1092b6f9d1/example/lib/pages/home_page.dart#L42-L46

Expect the problem to be fixed.

**Comment by ibhanu** [comment]
Another way of how I solved the problem was by removing placeholder!

**Comment by ggirotto** [comment]
I can confirm this happens when adding a `placeholder` to the editor.

**Comment by apoleo88** [comment]
I encountered this error when I added `placeholder` to QuillEditor
```
QuillEditor(
  controller: contentQuillController,
  scrollController: ScrollController(),
  scrollable: true,
  focusNode: FocusNode(),
  readOnly: false,
  autoFocus: false,
  expands: false,
  placeholder: "Description",
  padding: EdgeInsets.all(2)
)
```

<details>
  <summary>Exception log:</summary>
```
======= Exception caught by rendering library ==========
The following message was thrown during paint():
targetChild should not be null

The relevant error-causing widget was: 
  QuillEditor QuillEditor:/lib/page/edit.dart:366:38
When the exception was thrown, this was the stack: 
#0      RenderEditableContainerBox.childAtPosition (package:flutter_quill/src/widgets/editor.dart:1198:7)
#1      RenderEditor._getOffsetForCaret (package:flutter_quill/src/widgets/editor.dart:741:19)
#2      RenderEditor._updateSelectionExtentsVisibility (package:flutter_quill/src/widgets/editor.dart:717:25)
#3      RenderEditor.paint (package:flutter_quill/src/widgets/editor.dart:1010:5)
#4      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2409:7)
#5      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#6      RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#7      PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:398:12)
#8      RenderLeaderLayer.paint (package:flutter/src/rendering/proxy_box.dart:5131:13)
#9      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2409:7)
#10     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#11     _RenderSingleChildViewport.paint.paintContents (package:flutter_quill/src/widgets/quill_single_child_scroll_view.dart:251:17)
#12     _RenderSingleChildViewport.paint (package:flutter_quill/src/widgets/quill_single_child_scroll_view.dart:264:9)
#13     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2409:7)
#14     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:141:11)
#15     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:100:5)
#16     PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:979:29)
#17     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:455:19)
#18     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:883:13)
#19     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:319:5)
#20     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1143:15)
#21     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1080:9)
#22     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:996:5)
#26     _invoke (dart:ui/hooks.dart:166:10)
#27     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:270:5)
#28     _drawFrame (dart:ui/hooks.dart:129:31)
(elided 3 frames from dart:async)
The following RenderObject was being processed when the exception was fired: RenderEditor#298a6 relayoutBoundary=up37
...  needs compositing
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(0.0<=w<=292.0, 0.0<=h<=Infinity)
...  size: Size(292.0, 34.0)
RenderObject: RenderEditor#298a6 relayoutBoundary=up37
  needs compositing
  parentData: <none> (can use size)
  constraints: BoxConstraints(0.0<=w<=292.0, 0.0<=h<=Infinity)
  size: Size(292.0, 34.0)
```
</details>

**Comment by Hamza5** [comment]
This error happens on the Web too, when the `QuillEditor` has `placeholder` text set.

Any workaround to get rid of this exception without removing the placeholder text? It is very useful and I don't want to remove it.

**Comment by TaiTrien** [comment]
Any solutions? I meet the same issue

**Comment by ysyfff** [comment]
meet the same issue with placeholder

**Comment by WingCH** [comment]
meet the same issue with placeholder

**Comment by sonysm** [comment]
I face this problem too when adding placeholder
Any solution please?

**Comment by TaiTrien** [comment]
Hi guys,
In my case, I realized that the error just come with the simulators. I tried it on my real device and it worked

**Comment by MagTuxGit** [comment]
I did the next fix
https://github.com/MagTuxGit/flutter-quill/commit/28795c951b22b713cc66198401934a298ddbc4f2
Is it ok?

**Comment by singerdmx** [comment]
> I did the next fix
> 
> https://github.com/MagTuxGit/flutter-quill/commit/28795c951b22b713cc66198401934a298ddbc4f2
> 
> Is it ok?

Please submit a PR
