### ISSUE TITLE
[Mobile] select all text and click alignment button will throw error

### ISSUE THREAD

**Issue by innwin** [singerdmx/flutter-quill#384]
My issue is about [Mobile]

select all text and click alignment button will throw error

**Comment by singerdmx** [comment]
@innwin please add more details - at least what error it is

**Comment by aldycool** [comment]
I've managed to reproduce the bug here:

```
════════ Exception caught by foundation library ════════════════════════════════
The following assertion was thrown while dispatching notifications for ValueNotifier<Color>:
'package:flutter/src/rendering/object.dart': Failed assertion: line 2221 pos 12: '!_debugDisposed': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack
#2      RenderObject.markNeedsPaint
#3      ChangeNotifier.notifyListeners
#4      ValueNotifier.value=
#5      CursorCont._onColorTick
#6      AnimationLocalListenersMixin.notifyListeners
#7      AnimationController._tick
#8      Ticker._tick
#9      SchedulerBinding._invokeFrameCallback
#10     SchedulerBinding.handleBeginFrame.<anonymous closure>
#11     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:400:8)
#12     SchedulerBinding.handleBeginFrame
#13     SchedulerBinding._handleBeginFrame
#17     _invoke1 (dart:ui/hooks.dart:185:10)
#18     PlatformDispatcher._beginFrame (dart:ui/platform_dispatcher.dart:248:5)
#19     _beginFrame (dart:ui/hooks.dart:116:31)
(elided 5 frames from class _AssertionError and dart:async)
The ValueNotifier<Color> sending notification was: ValueNotifier<Color>#4cc14(Color(0x1c2196f3))
════════════════════════════════════════════════════════════════════════════════
```

The screenshot:

![image](https://user-images.githubusercontent.com/8155468/132797831-8f133451-ad40-4f19-a724-c663dab3d039.png)

Somehow (I think based on the assertion) something is affecting the cursor, `widgets/cursor.dart`, on `_onColorTick()`. I'll check more as soon as possible.

**Comment by aldycool** [comment]
After checking with latest `flutter-quill` release (2.0.3), this issue is not exist anymore.  The following shows videos of test using Android emulator and iOS Simulator:


https://user-images.githubusercontent.com/8155468/132933217-e9aff07c-0113-4025-9947-cee57239e323.mov


https://user-images.githubusercontent.com/8155468/132933234-d990bfa4-e047-4987-9f7a-568d9357601a.mov


@innwin , please try this setup (flutter-quill 2.0.3 / latest) with Flutter SDK 2.5.0 on your side and see if it works like mine.

**Comment by innwin** [comment]
problem solved, thx
