### ISSUE TITLE
[Desktop] Pressing backspace key or delete key to delete the selection throws exception 

### ISSUE THREAD

**Issue by sagarkardani** [singerdmx/flutter-quill#798]
#### Steps to reproduce
on platform windows
1. Select some text to delete
2. Press Delete key or Backspace key to delete the text

#### Expected behaviour

Pressing the delete key or backspace key should delete the selected text. Instead it throws below exception
<details><summary>exception</summary>
<p>

```
════════ Exception caught by services library ══════════════════════════════════
The following _CastError was thrown while processing the key message handler:
Null check operator used on a null value

When the exception was thrown, this was the stack
#0      Line.collectStyle
package:flutter_quill/…/nodes/line.dart:385
#1      Document.collectStyle
package:flutter_quill/…/documents/document.dart:157
#2      QuillController.getSelectionStyle
package:flutter_quill/…/widgets/controller.dart:87
#3      QuillController.replaceText
package:flutter_quill/…/widgets/controller.dart:188
#4      RawEditorStateSelectionDelegateMixin.textEditingValue=
package:flutter_quill/…/raw_editor/raw_editor_state_selection_delegate_mixin.dart:32
#5      RawEditorStateSelectionDelegateMixin.userUpdateTextEditingValue
package:flutter_quill/…/raw_editor/raw_editor_state_selection_delegate_mixin.dart:146
#6      RawEditorState._replaceText
package:flutter_quill/…/widgets/raw_editor.dart:909
#7      CallbackAction.invoke
package:flutter/…/widgets/actions.dart:534
#8      ActionDispatcher.invokeAction
package:flutter/…/widgets/actions.dart:573
#9      Actions.invoke.<anonymous closure>
package:flutter/…/widgets/actions.dart:872
#10     Actions._visitActionsAncestors
package:flutter/…/widgets/actions.dart:653
#11     Actions.invoke
package:flutter/…/widgets/actions.dart:866
#12     _DeleteTextAction.invoke
package:flutter_quill/…/widgets/raw_editor.dart:1555
#13     _OverridableContextAction.invokeDefaultAction
package:flutter/…/widgets/actions.dart:1691
#14     _OverridableActionMixin.invoke
package:flutter/…/widgets/actions.dart:1554
#15     ActionDispatcher.invokeAction
package:flutter/…/widgets/actions.dart:571
#16     ShortcutManager.handleKeypress
package:flutter/…/widgets/shortcuts.dart:728
#17     _ShortcutsState._handleOnKey
package:flutter/…/widgets/shortcuts.dart:929
#18     FocusManager._handleKeyMessage
package:flutter/…/widgets/focus_manager.dart:1593
#19     KeyEventManager.handleRawKeyMessage
package:flutter/…/services/hardware_keyboard.dart:832
#20     BasicMessageChannel.setMessageHandler.<anonymous closure>
package:flutter/…/services/platform_channel.dart:77
#21     BasicMessageChannel.setMessageHandler.<anonymous closure>
package:flutter/…/services/platform_channel.dart:76
#22     _DefaultBinaryMessenger.setMessageHandler.<anonymous closure>
package:flutter/…/services/binding.dart:377
#23     _DefaultBinaryMessenger.setMessageHandler.<anonymous closure>
package:flutter/…/services/binding.dart:374
#24     _invoke2.<anonymous closure> (dart:ui/hooks.dart:190:15)
#28     _invoke2 (dart:ui/hooks.dart:189:10)
#29     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:42:5)
#30     _Channel.push (dart:ui/channel_buffers.dart:132:31)
#31     ChannelBuffers.push (dart:ui/channel_buffers.dart:329:17)
#32     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:583:22)
#33     _dispatchPlatformMessage (dart:ui/hooks.dart:89:31)
(elided 3 frames from dart:async)
KeyMessage: KeyMessage([KeyDownEvent#18563(physicalKey: PhysicalKeyboardKey#7002a(usbHidUsage: "0x0007002a", debugName: "Backspace"), logicalKey: LogicalKeyboardKey#00008(keyId: "0x100000008", keyLabel: "Backspace", debugName: "Backspace"), character: null, timeStamp: 5:30:20.768411)])
════════════════════════════════════════════════════════════════════════════════
```

</p>
</details>

<details><summary>Minimal Reproducible Example</summary>
<p>

```dart
void main() {
  runApp(const MyTestApp());
}

class MyTestApp extends StatefulWidget {
  const MyTestApp({ Key? key }) : super(key: key);

  @override
  State<MyTestApp> createState() => _MyTestAppState();
}

class _MyTestAppState extends State<MyTestApp> {

  final ScrollController _scrollController = ScrollController();
  late final QuillController _quillController;

  @override
  void initState() {
    super.initState();
    final docJson = jsonDecode('''[{"insert": "My test text"}, {"insert": "\\n"}]''');
    _quillController = QuillController(
      document: Document.fromJson(docJson),
      selection: const TextSelection.collapsed(offset: 0),
      keepStyleOnNewLine: true,
    );
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'My Test App',
      home: Scaffold(
        appBar: AppBar(
          title: const SizedBox(
            child: Text('My Test App'),
          ),
        ),
        body: QuillEditor(
          controller: _quillController,
          focusNode: FocusNode(),
          scrollController: _scrollController,
          scrollable: true,
          padding: const EdgeInsets.only(left: 4, right: 4, top: 4),
          autoFocus: true,
          showCursor: true,
          readOnly: false,
          expands: true,
          textCapitalization: TextCapitalization.none,
          placeholder: 'Type a message here...',
        ),
      ),
    );
  }
}
```

</p>
</details>

<details><summary>flutter doctor</summary>
<p>

```
[√] Flutter (Channel stable, 2.10.1, on Microsoft Windows [Version 10.0.19043.1586], locale en-IN)
    • Flutter version 2.10.1 at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db747aa133 (3 months ago), 2022-02-09 13:57:35 -0600
    • Engine revision ab46186b24
    • Dart version 2.16.1
    • DevTools version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\Users\sagark\AppData\Local\Android\sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.0.6)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.0.32126.317
    • Windows 10 SDK version 10.0.20348.0

[√] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] VS Code (version 1.67.0)
    • VS Code at C:\Users\sagark\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.34.0

[√] Connected device (2 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19043.1586]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 100.0.4896.127

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

</p>
</details>

flutter_quill: ^4.1.7

Regards,
Sagar

**Comment by adrian-moisa** [comment]
I tested your example with version version: 4.1.3 on web + mac. Seems to be working just fine. Deletion works. Not sure if that helps you. maybe you have some sort of a callback dad does something ilegal. Or the delta that you are feeding in is corrupt. If you want to bounce more ideas join the [unofficial discord](https://discord.gg/XpGygmXde4). There's already a handful of people that are active in Quill. One of us might have an idea. Cheers!

**Comment by sagarkardani** [comment]
Hi @adrian-moisa,

Thanks for having a test.

I rechecked the Minimal Reproducible Example. So just running the app and selecting some text and deleting throws exception on **Windows** platform. I also tried running web build on **Chrome Windows** and it also throws exception.

> maybe you have some sort of a callback dad does something ilegal. Or the delta that you are feeding in is corrupt.

I didn't attach any callback and just run the Minimal Reproducible Example and I can reproduce the exception. You have already tested mac. So I think this problem is only with the **windows platform**.

**Comment by adrian-moisa** [comment]
Possibly, I don't have any windows machine on hand (Dell laptop died) but I can ask on [discord](https://discord.gg/XpGygmXde4) for people to check it out and get a confirmation on it.

**Comment by sagarkardani** [comment]
Oh Thanks...

**Comment by adrian-moisa** [comment]
No reply so far, still a growing community. Just started days ago
