### ISSUE TITLE
[Mobile] onTap Exception (StateError was thrown while handling a gesture) Bad state: No child at offset

### ISSUE THREAD

**Issue by Kulsum-kk2005256** [singerdmx/flutter-quill#855]
**I get the following exception after tapping on the QuillEditor on both Android and iOS. Sometimes it makes the 
 ui unresponsive and I cannot type anything on the editor.**

══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
The following StateError was thrown while handling a gesture:
Bad state: No child at offset Offset(147.2, 68.6).

When the exception was thrown, this was the stack:
#0      RenderEditableContainerBox.childAtOffset (package:flutter_quill/src/widgets/editor.dart:1719:5)
#1      RenderEditor.getPositionForOffset (package:flutter_quill/src/widgets/editor.dart:1244:19)
#2      RenderEditor.selectPositionAt (package:flutter_quill/src/widgets/editor.dart:1078:26)
#3      RenderEditor.selectPosition (package:flutter_quill/src/widgets/editor.dart:1106:5)
#4      _QuillEditorSelectionGestureDetectorBuilder.onSingleTapUp (package:flutter_quill/src/widgets/editor.dart:637:15)       
#5      _EditorTextSelectionGestureDetectorState._handleTapUp (package:flutter_quill/src/widgets/text_selection.dart:818:30)   
#6      TapGestureRecognizer.handleTapUp.<anonymous closure> (package:flutter/src/gestures/tap.dart:617:57)
#7      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:247:24)
#8      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:617:11)
#9      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:299:5)
#10     BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:269:7)
#11     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:163:27)
#12     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:454:20)
#13     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:430:22)
#14     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:337:11)
#15     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:385:7)
#16     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:347:5)
#17     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:304:7)
#18     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:285:7)
#19     _invoke1 (dart:ui/hooks.dart:167:13)
#20     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:341:7)
#21     _dispatchPointerDataPacket (dart:ui/hooks.dart:94:31)

Handler: "onTapUp"
Recognizer:
  _TransparentTapGestureRecognizer#aef22

════════════════════════════════════════════════════════════════════════════════════════════════════

Another exception was thrown: Bad state: No child at offset Offset(168.3, 86.4).

**Comment by adrian-moisa** [comment]
Can you share screenshots of your setup + delta document? There's too little info in this ticket.

**Comment by Kulsum-kk2005256** [comment]
I have added screenshots. Hope they are helpful.

**Comment by adrian-moisa** [comment]
You seem to have an empty doc, and you are tapping inside. I can't reproduce the error. There's something about your setup that is not obvious. Try creating a new project and a sample from scratch and check if this issue still manifests. And if not what do you have to change until it matches you app in order to trigger the error.

**Comment by Kulsum-kk2005256** [comment]
This exception doesn't occur when I use QuillEditor.basic instead of QuillEditor.
