### ISSUE TITLE
[Mobile] An Error Occurred While Updating To 5.2.3 And Newer Versions

### ISSUE THREAD

**Issue by BrahimAkar** [singerdmx/flutter-quill#897]
An Error Occurred While Updating To 5.2.3 And Newer Versions

My pubspec.yaml file contains the following libraries:
  ...  
  ...
  flutter_inappwebview: ^5.4.3+7
  flutter_quill: 5.3.2
  youtube_player_flutter: ^8.1.0

**NB:
 flutter_quill 5.2.2 And Older Versions Works just fine.**

**Debug console:**

```
Launching lib/main.dart on 2201116TG in debug mode...

ERROR:/Users/brahim/Documents/apps/my_app/build/flutter_inappwebview_quill/.transforms/303b257465faec16b824eb4ab2122743/transformed/classes/classes.dex: D8: Type com.pichillilorenzo.flutter_inappwebview.BuildConfig is defined multiple times: /Users/brahim/Documents/apps/my_app/build/flutter_inappwebview_quill/.transforms/303b257465faec16b824eb4ab2122743/transformed/classes/classes.dex, /Users/brahim/Documents/apps/my_app/build/flutter_inappwebview/.transforms/85a0cd361e44f4f9c95696fb86ed58c1/transformed/classes/classes.dex
com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
Type com.pichillilorenzo.flutter_inappwebview.BuildConfig is defined multiple times: /Users/brahim/Documents/apps/my_app/build/flutter_inappwebview_quill/.transforms/303b257465faec16b824eb4ab2122743/transformed/classes/classes.dex, /Users/brahim/Documents/apps/my_app/build/flutter_inappwebview/.transforms/85a0cd361e44f4f9c95696fb86ed58c1/transformed/classes/classes.dex
	at com.android.builder.dexing.D8DexArchiveMerger.getExceptionToRethrow(D8DexArchiveMerger.java:128)
	at com.android.builder.dexing.D8DexArchiveMerger.mergeDexArchives(D8DexArchiveMerger.java:115)
	at com.android.build.gradle.internal.transforms.DexMergerTransformCallable.call(DexMergerTransformCallable.java:111)
	at com.android.build.gradle.internal.tasks.DexMergingWorkAction.merge(DexMergingTask.kt:805)
	at com.android.build.gradle.internal.tasks.DexMergingWorkAction.run(DexMergingTask.kt:760)
	at com.android.build.gradle.internal.profile.ProfileAwareWorkAction.execute(ProfileAwareWorkAction.kt:74)
	at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:63)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.create(NoIsolationWorkerFactory.java:66)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.create(NoIsolationWorkerFactory.java:62)
	at org.gradle.internal.classloader.ClassLoaderUtils.executeInClassloader(ClassLoaderUtils.java:97)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1.lambda$execute$0(NoIsolationWorkerFactory.java:62)
	at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:44)
	at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:41)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:200)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:195)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:75)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:68)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:153)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:68)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:62)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.lambda$call$2(DefaultBuildOperationExecutor.java:76)
	at org.gradle.internal.operations.UnmanagedBuildOperationWrapper.callWithUnmanagedSupport(UnmanagedBuildOperationWrapper.java:54)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:76)
	at org.gradle.workers.internal.AbstractWorker.executeWrappedInBuildOperation(AbstractWorker.java:41)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1.execute(NoIsolationWorkerFactory.java:59)
	at org.gradle.workers.internal.DefaultWorkerExecutor.lambda$submitWork$2(DefaultWorkerExecutor.java:206)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runExecution(DefaultConditionalExecutionQueue.java:214)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runBatch(DefaultConditionalExecutionQueue.java:164)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.run(DefaultConditionalExecutionQueue.java:131)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: com.android.tools.r8.CompilationFailedException: Compilation failed to complete, origin: /Users/brahim/Documents/apps/my_app/build/flutter_inappwebview_quill/.transforms/303b257465faec16b824eb4ab2122743/transformed/classes/classes.dex
	at Version.fakeStackEntry(Version_2.2.64.java:0)
	at com.android.tools.r8.utils.a0.a(SourceFile:89)
	at com.android.tools.r8.D8.run(D8.java:11)
	at com.android.builder.dexing.D8DexArchiveMerger.mergeDexArchives(D8DexArchiveMerger.java:113)
	... 36 more
Caused by: com.android.tools.r8.utils.b: Type com.pichillilorenzo.flutter_inappwebview.BuildConfig is defined multiple times: /Users/brahim/Documents/apps/my_app/build/flutter_inappwebview_quill/.transforms/303b257465faec16b824eb4ab2122743/transformed/classes/classes.dex, /Users/brahim/Documents/apps/my_app/build/flutter_inappwebview/.transforms/85a0cd361e44f4f9c95696fb86ed58c1/transformed/classes/classes.dex
	at com.android.tools.r8.utils.V0.a(SourceFile:22)
	at com.android.tools.r8.utils.V0.a(SourceFile:25)
	at com.android.tools.r8.utils.T0.b(SourceFile:6)
	at com.android.tools.r8.utils.T0.a(SourceFile:24)
	at com.android.tools.r8.utils.T0.a(SourceFile:10)
	at java.base/java.util.concurrent.ConcurrentHashMap.merge(ConcurrentHashMap.java:2048)
	at com.android.tools.r8.utils.T0.a(SourceFile:6)
	at com.android.tools.r8.graph.i1$c.e(SourceFile:3)
	at com.android.tools.r8.dex.a.a(SourceFile:336)
	at com.android.tools.r8.dex.a.a(SourceFile:265)
	at com.android.tools.r8.D8.a(D8.java:22)
	at com.android.tools.r8.D8.d(D8.java:6)
	at com.android.tools.r8.D8.b(D8.java:1)
	at com.android.tools.r8.utils.a0.a(SourceFile:47)
	... 38 more

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeLibDexDebug'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.DexMergingTaskDelegate
   > There was a failure while executing work items
      > A failure occurred while executing com.android.build.gradle.internal.tasks.DexMergingWorkAction
         > com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
           Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
           Type com.pichillilorenzo.flutter_inappwebview.BuildConfig is defined multiple times: /Users/brahim/Documents/apps/my_app/build/flutter_inappwebview_quill/.transforms/303b257465faec16b824eb4ab2122743/transformed/classes/classes.dex, /Users/brahim/Documents/apps/my_app/build/flutter_inappwebview/.transforms/85a0cd361e44f4f9c95696fb86ed58c1/transformed/classes/classes.dex
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 35s
[!] App requires Multidex support
┌─ Flutter Fix ──────────────────────────────────────────────────────────────────────────────────┐
│ Flutter multidex handling is disabled. If you wish to let the tool configure multidex, use the │
│ --multidex flag.                                                                               │
└────────────────────────────────────────────────────────────────────────────────────────────────┘
Exception: Gradle task assembleDebug failed with exit code 1
Exited
```

**Comment by singerdmx** [comment]
Please clarify the steps to repro

**Comment by BrahimAkar** [comment]
Steps: 
1 - Either Create a new flutter project, or use an old one.
2 - Add those libraries to pubspec.yaml 
```  
  flutter_inappwebview: ^5.4.3+7
  flutter_quill: 5.3.2
  youtube_player_flutter: ^8.1.0
```
3 - flutter pub get
4 - Try To Run The app on mobile
5 - The above error will occured.


Flutter Version:

Flutter 3.0.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 85684f9300 (4 weeks ago) • 2022-06-30 13:22:47 -0700
Engine • revision 6ba2af10bb
Tools • Dart 2.17.5 • DevTools 2.12.2

**Comment by singerdmx** [comment]
Seems to be your local issue

**Comment by BrahimAkar** [comment]
Same error when building the app on a new machine [  Using a Github Runner with Latest Ubuntu Version ]

a screenshot from runner logs:

![error](https://user-images.githubusercontent.com/28510601/181960181-842140ad-1a09-415c-bd11-8c1d156790ff.png)

**Comment by amondnet** [comment]
https://github.com/garv-shah/flutter_inappwebview/blob/master/android/src/main/java/com/pichillilorenzo/flutter_inappwebview/InAppWebViewFlutterPlugin.java

has same package name.

**Comment by amondnet** [comment]
```yaml
dependency_overrides:
  flutter_inappwebview_quill:
    git:
      url: https://github.com/balancefriends/flutter_inappwebview.git
      ref: 4aae76557636349e856e6a010ce80f4685144cbf
```

**Comment by zacksleo** [comment]
`youtube_player_flutter_quill` depends on `flutter_inappwebview_quill` which conflicts with `flutter_inappwebview`

**Comment by amondnet** [comment]
Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Duplicate plugin key: InAppWebViewFlutterPlugin'

**Comment by amondnet** [comment]
```yaml
dependency_overrides:
  flutter_quill:
    git:
      url: https://github.com/balancefriends/flutter-quill.git
      ref: 509ab35a309e2840ae2e8dea7bd9739f42bde625
  flutter_inappwebview:
    git:
      url: https://github.com/CodeEagle/flutter_inappwebview.git
      ref: 06f87e81c4f55b7b251a149ec0db60442bb351c3
```

**Comment by singerdmx** [comment]
Please contact owner of youtube_player_flutter_quill

**Comment by singerdmx** [comment]
https://github.com/singerdmx/flutter-quill/commit/bf40b213161263ea30c117521152fa4a1821d256

We can revert this

**Comment by singerdmx** [comment]
We can remove youtube_player_flutter_quill and use youtube_player_flutter

**Comment by singerdmx** [comment]
```
dependency_overrides:
  url_launcher: ^6.1.2
  http_parser: ">=4.0.0"
  plugin_platform_interface: ">=2.0.0"
  xml: ^5.0.0
  analyzer: ^3.0.0
  math_keyboard: ^0.1.6
  flutter_math_fork: ^0.6.3+1
  flutter_svg: ^1.1.6
  flutter_quill_extensions:
    git:
      url: https://github.com/singerdmx/flutter-quill.git
      path: flutter_quill_extensions
```
