### ISSUE TITLE
[Mobile]: cannot paste file into editor from clibboard

### ISSUE THREAD

**Issue by ahmad-olu** [singerdmx/flutter-quill#918]
My issue is about [Mobile]

I have tried running `example` directory successfully before creating an issue here. 

i think my title is explanatory enogh... sorry
and the error i am getting below
```
Clipboard.getData (c:\src\flutter\flutter\packages\flutter\lib\src\services\clipboard.dart:54)
<asynchronous gap> (Unknown Source:0)
RawEditorState.pasteText (c:\src\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_quill-5.3.0\lib\src\widgets\raw_editor.dart:1015)
<asynchronous gap> (Unknown Source:0)
```
```
code:"error", details: null, and message:"Not supported, use openfile",
stacktrace: java.lang.IllegalArgumentException: Not supported, use openfile
    at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:172)
    at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:153)
    at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:781)
    at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1986)
    at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1924)
    at io.flutter.plugin.platform.PlatformPlugin.getClipboardData(PlatformPlugin.java:479)
    at io.flutter.plugin.platform.PlatformPlugin.access$900(PlatformPlugin.java:30)
    at io.flutter.plugin.platform.PlatformPlugin$1.getClipboardData(PlatformPlugin.java:119)
    at io.flutter.embedding.engine.systemchannels.PlatformChannel$1.onMethodCall(PlatformChannel.java:158)
    at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
    at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
    at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
    at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:246)
    at android.app.ActivityThread.main(ActivityThread.java:8512)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1139)
```

**Comment by singerdmx** [comment]
Clipboard won't be able to contain file. This is something fundamental from flutter. Not this library can address.

**Comment by ahmad-olu** [comment]
So how do I copy and paste into the library without a problem

**Comment by ahmad-olu** [comment]
Please can the creator of the package address this because the point you might want to write long notes so copy and paste from somewhere is easier to do

**Comment by friebetill** [comment]
[I have implemented](https://github.com/singerdmx/flutter-quill/pull/950) pasting images using the [pasteboard](https://pub.dev/packages/pasteboard) library. You can see how they access the images file in the respective operating systems and then copy it for the most part.

**Comment by ahmad-olu** [comment]
I am ready stopped using flutter quill package.
I know use quill js with flutter web view. So I just view it as a Web page on my app locally which has a lot of advantages but the disadvantage is that you would mostly want to read it on a webpage page. I could not find a better way around that.
Maybe anyone has other suggestions.
